// SPDX-FileCopyrightText: Copyright (C) 2023-2026 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)<lichtblick@bmwgroup.com>
// SPDX-License-Identifier: MPL-2.0

// Auto-generated by scripts/prepare-osi-version.mjs. Do not edit manually.
export const OSI_VERSION = "3.8.0";
