// SPDX-FileCopyrightText: Copyright (C) 2023-2026 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)<lichtblick@bmwgroup.com>
// SPDX-License-Identifier: MPL-2.0

export type LongLike = number | bigint | { toNumber(): number; toString(): string };

export enum osi3_LogicalDetectionClassification {
  LOGICAL_DETECTION_CLASSIFICATION_UNKNOWN = 0,
  LOGICAL_DETECTION_CLASSIFICATION_OTHER = 1,
  LOGICAL_DETECTION_CLASSIFICATION_INVALID = 2,
  LOGICAL_DETECTION_CLASSIFICATION_CLUTTER = 3,
  LOGICAL_DETECTION_CLASSIFICATION_OVERDRIVABLE = 4,
  LOGICAL_DETECTION_CLASSIFICATION_UNDERDRIVABLE = 5,
}

export enum osi3_LogicalDetectionDataHeader_DataQualifier {
  DATA_QUALIFIER_UNKNOWN = 0,
  DATA_QUALIFIER_OTHER = 1,
  DATA_QUALIFIER_AVAILABLE = 2,
  DATA_QUALIFIER_AVAILABLE_REDUCED = 3,
  DATA_QUALIFIER_NOT_AVAILABLE = 4,
  DATA_QUALIFIER_BLINDNESS = 5,
  DATA_QUALIFIER_TEMPORARY_AVAILABLE = 6,
  DATA_QUALIFIER_INVALID = 7,
}

export enum osi3_CameraDetection_ImageShapeType {
  IMAGE_SHAPE_TYPE_UNKNOWN = 0,
  IMAGE_SHAPE_TYPE_OTHER = 1,
  IMAGE_SHAPE_TYPE_POINT = 2,
  IMAGE_SHAPE_TYPE_BOX = 3,
  IMAGE_SHAPE_TYPE_ELLIPSE = 4,
  IMAGE_SHAPE_TYPE_POLYGON = 5,
  IMAGE_SHAPE_TYPE_POLYLINE = 6,
  IMAGE_SHAPE_TYPE_POINT_CLOUD = 7,
}

export enum osi3_CameraDetection_Color {
  COLOR_UNKNOWN = 0,
  COLOR_OTHER = 1,
  COLOR_BLACK = 2,
  COLOR_GRAY = 3,
  COLOR_GREY = 3,
  COLOR_WHITE = 4,
  COLOR_YELLOW = 5,
  COLOR_ORANGE = 6,
  COLOR_RED = 7,
  COLOR_VIOLET = 8,
  COLOR_BLUE = 9,
  COLOR_GREEN = 10,
  COLOR_REFLECTIVE = 11,
}

export enum osi3_SensorDetectionHeader_DataQualifier {
  DATA_QUALIFIER_UNKNOWN = 0,
  DATA_QUALIFIER_OTHER = 1,
  DATA_QUALIFIER_AVAILABLE = 2,
  DATA_QUALIFIER_AVAILABLE_REDUCED = 3,
  DATA_QUALIFIER_NOT_AVAILABLE = 4,
  DATA_QUALIFIER_BLINDNESS = 5,
  DATA_QUALIFIER_TEMPORARY_AVAILABLE = 6,
  DATA_QUALIFIER_INVALID = 7,
}

export enum osi3_SensorDetectionHeader_ExtendedQualifier {
  EXTENDED_QUALIFIER_UNKNOWN = 0,
  EXTENDED_QUALIFIER_OTHER = 1,
  EXTENDED_QUALIFIER_NORMAL_OPERATION_MODE = 2,
  EXTENDED_QUALIFIER_POWER_UP_OR_DOWN = 3,
  EXTENDED_QUALIFIER_SENSOR_NOT_CALIBRATED = 4,
  EXTENDED_QUALIFIER_SENSOR_BLOCKED = 5,
  EXTENDED_QUALIFIER_SENSOR_MISALIGNED = 6,
  EXTENDED_QUALIFIER_BAD_SENSOR_ENVIRONMENTAL_CONDITION = 7,
  EXTENDED_QUALIFIER_REDUCED_FIELD_OF_VIEW = 8,
  EXTENDED_QUALIFIER_INPUT_NOT_AVAILABLE = 9,
  EXTENDED_QUALIFIER_INTERNAL_REASON = 10,
  EXTENDED_QUALIFIER_EXTERNAL_DISTURBANCE = 11,
  EXTENDED_QUALIFIER_BEGINNING_BLOCKAGE = 12,
}

export enum osi3_DetectionClassification {
  DETECTION_CLASSIFICATION_UNKNOWN = 0,
  DETECTION_CLASSIFICATION_OTHER = 1,
  DETECTION_CLASSIFICATION_INVALID = 2,
  DETECTION_CLASSIFICATION_CLUTTER = 3,
  DETECTION_CLASSIFICATION_OVERDRIVABLE = 4,
  DETECTION_CLASSIFICATION_UNDERDRIVABLE = 5,
}

export enum osi3_Occupant_Classification_Seat {
  SEAT_UNKNOWN = 0,
  SEAT_OTHER = 1,
  SEAT_FRONT_LEFT = 2,
  SEAT_FRONT_RIGHT = 3,
  SEAT_FRONT_MIDDLE = 4,
  SEAT_BACK_LEFT = 5,
  SEAT_BACK_RIGHT = 6,
  SEAT_BACK_MIDDLE = 7,
  SEAT_THIRD_ROW_LEFT = 8,
  SEAT_THIRD_ROW_RIGHT = 9,
  SEAT_THIRD_ROW_MIDDLE = 10,
}

export enum osi3_Occupant_Classification_SteeringControl {
  STEERING_CONTROL_UNKNOWN = 0,
  STEERING_CONTROL_OTHER = 1,
  STEERING_CONTROL_NO_HAND = 2,
  STEERING_CONTROL_ONE_HAND = 3,
  STEERING_CONTROL_BOTH_HANDS = 4,
  STEERING_CONTROL_LEFT_HAND = 5,
  STEERING_CONTROL_RIGHT_HAND = 6,
}

export enum osi3_DetectedItemHeader_MeasurementState {
  MEASUREMENT_STATE_UNKNOWN = 0,
  MEASUREMENT_STATE_OTHER = 1,
  MEASUREMENT_STATE_MEASURED = 2,
  MEASUREMENT_STATE_PREDICTED = 3,
}

export enum osi3_DetectedEntityHeader_DataQualifier {
  DATA_QUALIFIER_UNKNOWN = 0,
  DATA_QUALIFIER_OTHER = 1,
  DATA_QUALIFIER_AVAILABLE = 2,
  DATA_QUALIFIER_AVAILABLE_REDUCED = 3,
  DATA_QUALIFIER_NOT_AVAILABLE = 4,
  DATA_QUALIFIER_BLINDNESS = 5,
  DATA_QUALIFIER_TEMPORARY_AVAILABLE = 6,
}

export enum osi3_Lane_Classification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_DRIVING = 2,
  TYPE_NONDRIVING = 3,
  TYPE_INTERSECTION = 4,
}

export enum osi3_Lane_Classification_Subtype {
  SUBTYPE_UNKNOWN = 0,
  SUBTYPE_OTHER = 1,
  SUBTYPE_NORMAL = 2,
  SUBTYPE_BIKING = 3,
  SUBTYPE_SIDEWALK = 4,
  SUBTYPE_PARKING = 5,
  SUBTYPE_STOP = 6,
  SUBTYPE_RESTRICTED = 7,
  SUBTYPE_BORDER = 8,
  SUBTYPE_SHOULDER = 9,
  SUBTYPE_EXIT = 10,
  SUBTYPE_ENTRY = 11,
  SUBTYPE_ONRAMP = 12,
  SUBTYPE_OFFRAMP = 13,
  SUBTYPE_CONNECTINGRAMP = 14,
}

export enum osi3_LaneBoundary_BoundaryPoint_Dash {
  DASH_UNKNOWN = 0,
  DASH_OTHER = 1,
  DASH_START = 2,
  DASH_CONTINUE = 3,
  DASH_END = 4,
  DASH_GAP = 5,
}

export enum osi3_LaneBoundary_Classification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_NO_LINE = 2,
  TYPE_SOLID_LINE = 3,
  TYPE_DASHED_LINE = 4,
  TYPE_BOTTS_DOTS = 5,
  TYPE_ROAD_EDGE = 6,
  TYPE_SNOW_EDGE = 7,
  TYPE_GRASS_EDGE = 8,
  TYPE_GRAVEL_EDGE = 9,
  TYPE_SOIL_EDGE = 10,
  TYPE_GUARD_RAIL = 11,
  TYPE_CURB = 12,
  TYPE_STRUCTURE = 13,
  TYPE_BARRIER = 14,
  TYPE_SOUND_BARRIER = 15,
}

export enum osi3_LaneBoundary_Classification_Color {
  COLOR_UNKNOWN = 0,
  COLOR_OTHER = 1,
  COLOR_NONE = 2,
  COLOR_WHITE = 3,
  COLOR_YELLOW = 4,
  COLOR_RED = 5,
  COLOR_BLUE = 6,
  COLOR_GREEN = 7,
  COLOR_VIOLET = 8,
  COLOR_ORANGE = 9,
}

export enum osi3_RoadMarking_Classification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_PAINTED_TRAFFIC_SIGN = 2,
  TYPE_SYMBOLIC_TRAFFIC_SIGN = 3,
  TYPE_TEXTUAL_TRAFFIC_SIGN = 4,
  TYPE_GENERIC_SYMBOL = 5,
  TYPE_GENERIC_LINE = 6,
  TYPE_GENERIC_TEXT = 7,
}

export enum osi3_TrafficSign_MainSign_Classification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_DANGER_SPOT = 2,
  TYPE_ZEBRA_CROSSING = 87,
  TYPE_FLIGHT = 110,
  TYPE_CATTLE = 200,
  TYPE_HORSE_RIDERS = 197,
  TYPE_AMPHIBIANS = 188,
  TYPE_FALLING_ROCKS = 96,
  TYPE_SNOW_OR_ICE = 94,
  TYPE_LOOSE_GRAVEL = 97,
  TYPE_WATERSIDE = 102,
  TYPE_CLEARANCE = 210,
  TYPE_MOVABLE_BRIDGE = 101,
  TYPE_RIGHT_BEFORE_LEFT_NEXT_INTERSECTION = 3,
  TYPE_TURN_LEFT = 4,
  TYPE_TURN_RIGHT = 5,
  TYPE_DOUBLE_TURN_LEFT = 6,
  TYPE_DOUBLE_TURN_RIGHT = 7,
  TYPE_HILL_DOWNWARDS = 8,
  TYPE_HILL_UPWARDS = 9,
  TYPE_UNEVEN_ROAD = 93,
  TYPE_ROAD_SLIPPERY_WET_OR_DIRTY = 95,
  TYPE_SIDE_WINDS = 98,
  TYPE_ROAD_NARROWING = 10,
  TYPE_ROAD_NARROWING_RIGHT = 12,
  TYPE_ROAD_NARROWING_LEFT = 11,
  TYPE_ROAD_WORKS = 13,
  TYPE_TRAFFIC_QUEUES = 100,
  TYPE_TWO_WAY_TRAFFIC = 14,
  TYPE_ATTENTION_TRAFFIC_LIGHT = 15,
  TYPE_PEDESTRIANS = 103,
  TYPE_CHILDREN_CROSSING = 106,
  TYPE_CYCLE_ROUTE = 107,
  TYPE_DEER_CROSSING = 109,
  TYPE_UNGATED_LEVEL_CROSSING = 144,
  TYPE_LEVEL_CROSSING_MARKER = 112,
  TYPE_RAILWAY_TRAFFIC_PRIORITY = 135,
  TYPE_GIVE_WAY = 16,
  TYPE_STOP = 17,
  TYPE_PRIORITY_TO_OPPOSITE_DIRECTION = 18,
  TYPE_PRIORITY_TO_OPPOSITE_DIRECTION_UPSIDE_DOWN = 19,
  TYPE_PRESCRIBED_LEFT_TURN = 20,
  TYPE_PRESCRIBED_RIGHT_TURN = 21,
  TYPE_PRESCRIBED_STRAIGHT = 22,
  TYPE_PRESCRIBED_RIGHT_WAY = 24,
  TYPE_PRESCRIBED_LEFT_WAY = 23,
  TYPE_PRESCRIBED_RIGHT_TURN_AND_STRAIGHT = 26,
  TYPE_PRESCRIBED_LEFT_TURN_AND_STRAIGHT = 25,
  TYPE_PRESCRIBED_LEFT_TURN_AND_RIGHT_TURN = 27,
  TYPE_PRESCRIBED_LEFT_TURN_RIGHT_TURN_AND_STRAIGHT = 28,
  TYPE_ROUNDABOUT = 29,
  TYPE_ONEWAY_LEFT = 30,
  TYPE_ONEWAY_RIGHT = 31,
  TYPE_PASS_LEFT = 32,
  TYPE_PASS_RIGHT = 33,
  TYPE_SIDE_LANE_OPEN_FOR_TRAFFIC = 128,
  TYPE_SIDE_LANE_CLOSED_FOR_TRAFFIC = 129,
  TYPE_SIDE_LANE_CLOSING_FOR_TRAFFIC = 130,
  TYPE_BUS_STOP = 137,
  TYPE_TAXI_STAND = 138,
  TYPE_BICYCLES_ONLY = 145,
  TYPE_HORSE_RIDERS_ONLY = 146,
  TYPE_PEDESTRIANS_ONLY = 147,
  TYPE_BICYCLES_PEDESTRIANS_SHARED_ONLY = 148,
  TYPE_BICYCLES_PEDESTRIANS_SEPARATED_LEFT_ONLY = 149,
  TYPE_BICYCLES_PEDESTRIANS_SEPARATED_RIGHT_ONLY = 150,
  TYPE_PEDESTRIAN_ZONE_BEGIN = 151,
  TYPE_PEDESTRIAN_ZONE_END = 152,
  TYPE_BICYCLE_ROAD_BEGIN = 153,
  TYPE_BICYCLE_ROAD_END = 154,
  TYPE_BUS_LANE = 34,
  TYPE_BUS_LANE_BEGIN = 35,
  TYPE_BUS_LANE_END = 36,
  TYPE_ALL_PROHIBITED = 37,
  TYPE_MOTORIZED_MULTITRACK_PROHIBITED = 38,
  TYPE_TRUCKS_PROHIBITED = 39,
  TYPE_BICYCLES_PROHIBITED = 40,
  TYPE_MOTORCYCLES_PROHIBITED = 41,
  TYPE_MOPEDS_PROHIBITED = 155,
  TYPE_HORSE_RIDERS_PROHIBITED = 156,
  TYPE_HORSE_CARRIAGES_PROHIBITED = 157,
  TYPE_CATTLE_PROHIBITED = 158,
  TYPE_BUSES_PROHIBITED = 159,
  TYPE_CARS_PROHIBITED = 160,
  TYPE_CARS_TRAILERS_PROHIBITED = 161,
  TYPE_TRUCKS_TRAILERS_PROHIBITED = 162,
  TYPE_TRACTORS_PROHIBITED = 163,
  TYPE_PEDESTRIANS_PROHIBITED = 42,
  TYPE_MOTOR_VEHICLES_PROHIBITED = 43,
  TYPE_HAZARDOUS_GOODS_VEHICLES_PROHIBITED = 164,
  TYPE_OVER_WEIGHT_VEHICLES_PROHIBITED = 165,
  TYPE_VEHICLES_AXLE_OVER_WEIGHT_PROHIBITED = 166,
  TYPE_VEHICLES_EXCESS_WIDTH_PROHIBITED = 167,
  TYPE_VEHICLES_EXCESS_HEIGHT_PROHIBITED = 168,
  TYPE_VEHICLES_EXCESS_LENGTH_PROHIBITED = 169,
  TYPE_DO_NOT_ENTER = 44,
  TYPE_SNOW_CHAINS_REQUIRED = 170,
  TYPE_WATER_POLLUTANT_VEHICLES_PROHIBITED = 171,
  TYPE_ENVIRONMENTAL_ZONE_BEGIN = 45,
  TYPE_ENVIRONMENTAL_ZONE_END = 46,
  TYPE_NO_U_TURN_LEFT = 47,
  TYPE_NO_U_TURN_RIGHT = 48,
  TYPE_PRESCRIBED_U_TURN_LEFT = 49,
  TYPE_PRESCRIBED_U_TURN_RIGHT = 50,
  TYPE_MINIMUM_DISTANCE_FOR_TRUCKS = 51,
  TYPE_SPEED_LIMIT_BEGIN = 52,
  TYPE_SPEED_LIMIT_ZONE_BEGIN = 53,
  TYPE_SPEED_LIMIT_ZONE_END = 54,
  TYPE_MINIMUM_SPEED_BEGIN = 55,
  TYPE_OVERTAKING_BAN_BEGIN = 56,
  TYPE_OVERTAKING_BAN_FOR_TRUCKS_BEGIN = 57,
  TYPE_SPEED_LIMIT_END = 58,
  TYPE_MINIMUM_SPEED_END = 59,
  TYPE_OVERTAKING_BAN_END = 60,
  TYPE_OVERTAKING_BAN_FOR_TRUCKS_END = 61,
  TYPE_ALL_RESTRICTIONS_END = 62,
  TYPE_NO_STOPPING = 63,
  TYPE_NO_PARKING = 64,
  TYPE_NO_PARKING_ZONE_BEGIN = 65,
  TYPE_NO_PARKING_ZONE_END = 66,
  TYPE_RIGHT_OF_WAY_NEXT_INTERSECTION = 67,
  TYPE_RIGHT_OF_WAY_BEGIN = 68,
  TYPE_RIGHT_OF_WAY_END = 69,
  TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION = 70,
  TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION_UPSIDE_DOWN = 71,
  TYPE_TOWN_BEGIN = 72,
  TYPE_TOWN_END = 73,
  TYPE_CAR_PARKING = 74,
  TYPE_CAR_PARKING_ZONE_BEGIN = 75,
  TYPE_CAR_PARKING_ZONE_END = 76,
  TYPE_SIDEWALK_HALF_PARKING_LEFT = 172,
  TYPE_SIDEWALK_HALF_PARKING_RIGHT = 173,
  TYPE_SIDEWALK_PARKING_LEFT = 174,
  TYPE_SIDEWALK_PARKING_RIGHT = 175,
  TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_LEFT = 176,
  TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_RIGHT = 177,
  TYPE_SIDEWALK_PERPENDICULAR_PARKING_LEFT = 178,
  TYPE_SIDEWALK_PERPENDICULAR_PARKING_RIGHT = 179,
  TYPE_LIVING_STREET_BEGIN = 77,
  TYPE_LIVING_STREET_END = 78,
  TYPE_TUNNEL = 79,
  TYPE_EMERGENCY_STOPPING_LEFT = 80,
  TYPE_EMERGENCY_STOPPING_RIGHT = 81,
  TYPE_HIGHWAY_BEGIN = 82,
  TYPE_HIGHWAY_END = 83,
  TYPE_EXPRESSWAY_BEGIN = 84,
  TYPE_EXPRESSWAY_END = 85,
  TYPE_NAMED_HIGHWAY_EXIT = 183,
  TYPE_NAMED_EXPRESSWAY_EXIT = 184,
  TYPE_NAMED_ROAD_EXIT = 185,
  TYPE_HIGHWAY_EXIT = 86,
  TYPE_EXPRESSWAY_EXIT = 186,
  TYPE_ONEWAY_STREET = 187,
  TYPE_CROSSING_GUARDS = 189,
  TYPE_DEADEND = 190,
  TYPE_DEADEND_EXCLUDING_DESIGNATED_ACTORS = 191,
  TYPE_FIRST_AID_STATION = 194,
  TYPE_POLICE_STATION = 195,
  TYPE_TELEPHONE = 196,
  TYPE_FILLING_STATION = 198,
  TYPE_HOTEL = 201,
  TYPE_INN = 202,
  TYPE_KIOSK = 203,
  TYPE_TOILET = 204,
  TYPE_CHAPEL = 205,
  TYPE_TOURIST_INFO = 206,
  TYPE_REPAIR_SERVICE = 207,
  TYPE_PEDESTRIAN_UNDERPASS = 208,
  TYPE_PEDESTRIAN_BRIDGE = 209,
  TYPE_CAMPER_PLACE = 213,
  TYPE_ADVISORY_SPEED_LIMIT_BEGIN = 214,
  TYPE_ADVISORY_SPEED_LIMIT_END = 215,
  TYPE_PLACE_NAME = 216,
  TYPE_TOURIST_ATTRACTION = 217,
  TYPE_TOURIST_ROUTE = 218,
  TYPE_TOURIST_AREA = 219,
  TYPE_SHOULDER_NOT_PASSABLE_MOTOR_VEHICLES = 220,
  TYPE_SHOULDER_UNSAFE_TRUCKS_TRACTORS = 221,
  TYPE_TOLL_BEGIN = 222,
  TYPE_TOLL_END = 223,
  TYPE_TOLL_ROAD = 224,
  TYPE_CUSTOMS = 225,
  TYPE_INTERNATIONAL_BORDER_INFO = 226,
  TYPE_STREETLIGHT_RED_BAND = 227,
  TYPE_FEDERAL_HIGHWAY_ROUTE_NUMBER = 228,
  TYPE_HIGHWAY_ROUTE_NUMBER = 229,
  TYPE_HIGHWAY_INTERCHANGE_NUMBER = 230,
  TYPE_EUROPEAN_ROUTE_NUMBER = 231,
  TYPE_FEDERAL_HIGHWAY_DIRECTION_LEFT = 232,
  TYPE_FEDERAL_HIGHWAY_DIRECTION_RIGHT = 233,
  TYPE_PRIMARY_ROAD_DIRECTION_LEFT = 234,
  TYPE_PRIMARY_ROAD_DIRECTION_RIGHT = 235,
  TYPE_SECONDARY_ROAD_DIRECTION_LEFT = 236,
  TYPE_SECONDARY_ROAD_DIRECTION_RIGHT = 237,
  TYPE_DIRECTION_DESIGNATED_ACTORS_LEFT = 238,
  TYPE_DIRECTION_DESIGNATED_ACTORS_RIGHT = 239,
  TYPE_ROUTING_DESIGNATED_ACTORS = 240,
  TYPE_DIRECTION_TO_HIGHWAY_LEFT = 143,
  TYPE_DIRECTION_TO_HIGHWAY_RIGHT = 108,
  TYPE_DIRECTION_TO_LOCAL_DESTINATION_LEFT = 127,
  TYPE_DIRECTION_TO_LOCAL_DESTINATION_RIGHT = 136,
  TYPE_CONSOLIDATED_DIRECTIONS = 118,
  TYPE_STREET_NAME = 119,
  TYPE_DIRECTION_PREANNOUNCEMENT = 120,
  TYPE_DIRECTION_PREANNOUNCEMENT_LANE_CONFIG = 121,
  TYPE_DIRECTION_PREANNOUNCEMENT_HIGHWAY_ENTRIES = 122,
  TYPE_HIGHWAY_ANNOUNCEMENT = 123,
  TYPE_OTHER_ROAD_ANNOUNCEMENT = 124,
  TYPE_HIGHWAY_ANNOUNCEMENT_TRUCK_STOP = 125,
  TYPE_HIGHWAY_PREANNOUNCEMENT_DIRECTIONS = 126,
  TYPE_POLE_EXIT = 88,
  TYPE_HIGHWAY_DISTANCE_BOARD = 180,
  TYPE_DETOUR_LEFT = 181,
  TYPE_DETOUR_RIGHT = 182,
  TYPE_NUMBERED_DETOUR = 131,
  TYPE_DETOUR_BEGIN = 132,
  TYPE_DETOUR_END = 133,
  TYPE_DETOUR_ROUTING_BOARD = 134,
  TYPE_OPTIONAL_DETOUR = 111,
  TYPE_OPTIONAL_DETOUR_ROUTING = 199,
  TYPE_ROUTE_RECOMMENDATION = 211,
  TYPE_ROUTE_RECOMMENDATION_END = 212,
  TYPE_ANNOUNCE_LANE_TRANSITION_LEFT = 192,
  TYPE_ANNOUNCE_LANE_TRANSITION_RIGHT = 193,
  TYPE_ANNOUNCE_RIGHT_LANE_END = 90,
  TYPE_ANNOUNCE_LEFT_LANE_END = 89,
  TYPE_ANNOUNCE_RIGHT_LANE_BEGIN = 115,
  TYPE_ANNOUNCE_LEFT_LANE_BEGIN = 116,
  TYPE_ANNOUNCE_LANE_CONSOLIDATION = 117,
  TYPE_DETOUR_CITY_BLOCK = 142,
  TYPE_GATE = 141,
  TYPE_POLE_WARNING = 91,
  TYPE_TRAFFIC_CONE = 140,
  TYPE_MOBILE_LANE_CLOSURE = 139,
  TYPE_REFLECTOR_POST = 114,
  TYPE_DIRECTIONAL_BOARD_WARNING = 113,
  TYPE_GUIDING_PLATE = 104,
  TYPE_GUIDING_PLATE_WEDGES = 105,
  TYPE_PARKING_HAZARD = 99,
  TYPE_TRAFFIC_LIGHT_GREEN_ARROW = 92,
}

export enum osi3_RoadMarking_Classification_Color {
  COLOR_UNKNOWN = 0,
  COLOR_OTHER = 1,
  COLOR_WHITE = 2,
  COLOR_YELLOW = 3,
  COLOR_BLUE = 5,
  COLOR_RED = 6,
  COLOR_GREEN = 7,
  COLOR_VIOLET = 8,
  COLOR_ORANGE = 9,
}

export enum osi3_TrafficSignValue_Unit {
  UNIT_UNKNOWN = 0,
  UNIT_OTHER = 1,
  UNIT_NO_UNIT = 2,
  UNIT_KILOMETER_PER_HOUR = 3,
  UNIT_MILE_PER_HOUR = 4,
  UNIT_METER = 5,
  UNIT_KILOMETER = 6,
  UNIT_FEET = 7,
  UNIT_MILE = 8,
  UNIT_METRIC_TON = 9,
  UNIT_LONG_TON = 10,
  UNIT_SHORT_TON = 11,
  UNIT_HOUR = 15,
  UNIT_MINUTES = 12,
  UNIT_DAY_OF_MONTH = 16,
  UNIT_DAY = 13,
  UNIT_PERCENTAGE = 14,
  UNIT_DURATION_DAY = 17,
  UNIT_DURATION_HOUR = 18,
  UNIT_DURATION_MINUTE = 19,
}

export enum osi3_BoundingBox_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_BASE_STRUCTURE = 2,
  TYPE_PROTRUDING_STRUCTURE = 3,
  TYPE_CARGO = 4,
  TYPE_DOOR = 5,
  TYPE_SIDE_MIRROR = 6,
}

export enum osi3_TrafficLight_Classification_Color {
  COLOR_UNKNOWN = 0,
  COLOR_OTHER = 1,
  COLOR_RED = 2,
  COLOR_YELLOW = 3,
  COLOR_GREEN = 4,
  COLOR_BLUE = 5,
  COLOR_WHITE = 6,
}

export enum osi3_TrafficLight_Classification_Icon {
  ICON_UNKNOWN = 0,
  ICON_OTHER = 1,
  ICON_NONE = 2,
  ICON_ARROW_STRAIGHT_AHEAD = 3,
  ICON_ARROW_LEFT = 4,
  ICON_ARROW_DIAG_LEFT = 5,
  ICON_ARROW_STRAIGHT_AHEAD_LEFT = 6,
  ICON_ARROW_RIGHT = 7,
  ICON_ARROW_DIAG_RIGHT = 8,
  ICON_ARROW_STRAIGHT_AHEAD_RIGHT = 9,
  ICON_ARROW_LEFT_RIGHT = 10,
  ICON_ARROW_DOWN = 11,
  ICON_ARROW_DOWN_LEFT = 12,
  ICON_ARROW_DOWN_RIGHT = 13,
  ICON_ARROW_CROSS = 14,
  ICON_PEDESTRIAN = 15,
  ICON_WALK = 16,
  ICON_DONT_WALK = 17,
  ICON_BICYCLE = 18,
  ICON_PEDESTRIAN_AND_BICYCLE = 19,
  ICON_COUNTDOWN_SECONDS = 20,
  ICON_COUNTDOWN_PERCENT = 21,
  ICON_TRAM = 22,
  ICON_BUS = 23,
  ICON_BUS_AND_TRAM = 24,
}

export enum osi3_TrafficLight_Classification_Mode {
  MODE_UNKNOWN = 0,
  MODE_OTHER = 1,
  MODE_OFF = 2,
  MODE_CONSTANT = 3,
  MODE_FLASHING = 4,
  MODE_COUNTING = 5,
}

export enum osi3_TrafficSign_Variability {
  VARIABILITY_UNKNOWN = 0,
  VARIABILITY_OTHER = 1,
  VARIABILITY_FIXED = 2,
  VARIABILITY_VARIABLE = 3,
  VARIABILITY_MOVABLE = 4,
  VARIABILITY_MUTABLE = 5,
  VARIABILITY_MOVABLE_AND_MUTABLE = 6,
}

export enum osi3_TrafficSign_SupplementarySign_Classification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_NO_SIGN = 2,
  TYPE_TEXT = 41,
  TYPE_SPACE = 39,
  TYPE_TIME = 26,
  TYPE_ARROW = 30,
  TYPE_CONSTRAINED_TO = 46,
  TYPE_EXCEPT = 45,
  TYPE_VALID_FOR_DISTANCE = 3,
  TYPE_PRIORITY_ROAD_BOTTOM_LEFT_FOUR_WAY = 27,
  TYPE_PRIORITY_ROAD_TOP_LEFT_FOUR_WAY = 28,
  TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_STRAIGHT = 32,
  TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_SIDEWAYS = 33,
  TYPE_PRIORITY_ROAD_TOP_LEFT_THREE_WAY_STRAIGHT = 34,
  TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_FOUR_WAY = 29,
  TYPE_PRIORITY_ROAD_TOP_RIGHT_FOUR_WAY = 31,
  TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_STRAIGHT = 35,
  TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_SIDEWAY = 36,
  TYPE_PRIORITY_ROAD_TOP_RIGHT_THREE_WAY_STRAIGHT = 37,
  TYPE_VALID_IN_DISTANCE = 4,
  TYPE_STOP_IN = 25,
  TYPE_LEFT_ARROW = 11,
  TYPE_LEFT_BEND_ARROW = 13,
  TYPE_RIGHT_ARROW = 12,
  TYPE_RIGHT_BEND_ARROW = 14,
  TYPE_ACCIDENT = 40,
  TYPE_SNOW = 9,
  TYPE_FOG = 8,
  TYPE_ROLLING_HIGHWAY_INFORMATION = 48,
  TYPE_SERVICES = 47,
  TYPE_TIME_RANGE = 5,
  TYPE_PARKING_DISC_TIME_RESTRICTION = 43,
  TYPE_WEIGHT = 6,
  TYPE_WET = 44,
  TYPE_PARKING_CONSTRAINT = 42,
  TYPE_NO_WAITING_SIDE_STRIPES = 38,
  TYPE_RAIN = 7,
  TYPE_SNOW_RAIN = 10,
  TYPE_NIGHT = 19,
  TYPE_STOP_4_WAY = 21,
  TYPE_TRUCK = 15,
  TYPE_TRACTORS_MAY_BE_PASSED = 16,
  TYPE_HAZARDOUS = 17,
  TYPE_TRAILER = 18,
  TYPE_ZONE = 20,
  TYPE_MOTORCYCLE = 22,
  TYPE_MOTORCYCLE_ALLOWED = 23,
  TYPE_CAR = 24,
}

export enum osi3_TrafficSign_SupplementarySign_Classification_Actor {
  ACTOR_UNKNOWN = 0,
  ACTOR_OTHER = 1,
  ACTOR_NO_ACTOR = 2,
  ACTOR_AGRICULTURAL_VEHICLES = 3,
  ACTOR_BICYCLES = 4,
  ACTOR_BUSES = 5,
  ACTOR_CAMPERS = 6,
  ACTOR_CARAVANS = 7,
  ACTOR_CARS = 8,
  ACTOR_CARS_WITH_CARAVANS = 9,
  ACTOR_CARS_WITH_TRAILERS = 10,
  ACTOR_CATTLE = 11,
  ACTOR_CHILDREN = 12,
  ACTOR_CONSTRUCTION_VEHICLES = 13,
  ACTOR_DELIVERY_VEHICLES = 14,
  ACTOR_DISABLED_PERSONS = 15,
  ACTOR_EBIKES = 16,
  ACTOR_ELECTRIC_VEHICLES = 17,
  ACTOR_EMERGENCY_VEHICLES = 18,
  ACTOR_FERRY_USERS = 19,
  ACTOR_FORESTRY_VEHICLES = 20,
  ACTOR_HAZARDOUS_GOODS_VEHICLES = 21,
  ACTOR_HORSE_CARRIAGES = 22,
  ACTOR_HORSE_RIDERS = 23,
  ACTOR_INLINE_SKATERS = 24,
  ACTOR_MEDICAL_VEHICLES = 25,
  ACTOR_MILITARY_VEHICLES = 26,
  ACTOR_MOPEDS = 27,
  ACTOR_MOTORCYCLES = 28,
  ACTOR_MOTORIZED_MULTITRACK_VEHICLES = 29,
  ACTOR_OPERATIONAL_AND_UTILITY_VEHICLES = 30,
  ACTOR_PEDESTRIANS = 31,
  ACTOR_PUBLIC_TRANSPORT_VEHICLES = 32,
  ACTOR_RAILROAD_TRAFFIC = 33,
  ACTOR_RESIDENTS = 34,
  ACTOR_SLURRY_TRANSPORT = 35,
  ACTOR_TAXIS = 36,
  ACTOR_TRACTORS = 37,
  ACTOR_TRAILERS = 38,
  ACTOR_TRAMS = 39,
  ACTOR_TRUCKS = 40,
  ACTOR_TRUCKS_WITH_SEMITRAILERS = 41,
  ACTOR_TRUCKS_WITH_TRAILERS = 42,
  ACTOR_VEHICLES_WITH_GREEN_BADGES = 43,
  ACTOR_VEHICLES_WITH_RED_BADGES = 44,
  ACTOR_VEHICLES_WITH_YELLOW_BADGES = 45,
  ACTOR_WATER_POLLUTANT_VEHICLES = 46,
  ACTOR_WINTER_SPORTSPEOPLE = 47,
}

export enum osi3_TrafficSign_SupplementarySign_Classification_Arrow_Direction {
  DIRECTION_UNKNOWN = 0,
  DIRECTION_OTHER = 1,
  DIRECTION_NO_DIRECTION = 2,
  DIRECTION_DIRECT_0_DEG = 3,
  DIRECTION_DIRECT_45_DEG_RIGHT = 4,
  DIRECTION_DIRECT_45_DEG_LEFT = 5,
  DIRECTION_DIRECT_90_DEG_RIGHT = 6,
  DIRECTION_DIRECT_90_DEG_LEFT = 7,
  DIRECTION_DIRECT_135_DEG_RIGHT = 8,
  DIRECTION_DIRECT_135_DEG_LEFT = 9,
  DIRECTION_DIRECT_180_DEG = 10,
  DIRECTION_TURN_45_DEG_RIGHT = 11,
  DIRECTION_TURN_45_DEG_LEFT = 12,
  DIRECTION_TURN_90_DEG_RIGHT = 13,
  DIRECTION_TURN_90_DEG_LEFT = 14,
  DIRECTION_TURN_135_DEG_RIGHT = 15,
  DIRECTION_TURN_135_DEG_LEFT = 16,
  DIRECTION_TURN_180_DEG_RIGHT = 17,
  DIRECTION_TURN_180_DEG_LEFT = 18,
  DIRECTION_CIRCLE_0_DEG = 19,
  DIRECTION_CIRCLE_45_DEG_RIGHT = 20,
  DIRECTION_CIRCLE_45_DEG_LEFT = 21,
  DIRECTION_CIRCLE_90_DEG_RIGHT = 22,
  DIRECTION_CIRCLE_90_DEG_LEFT = 23,
  DIRECTION_CIRCLE_135_DEG_RIGHT = 24,
  DIRECTION_CIRCLE_135_DEG_LEFT = 25,
  DIRECTION_CIRCLE_180_DEG = 26,
  DIRECTION_KEEP_LEFT_TO_TURN_0_DEG = 27,
  DIRECTION_KEEP_RIGHT_TO_TURN_0_DEG = 28,
  DIRECTION_KEEP_LEFT_TO_TURN_90_DEG_RIGHT = 29,
  DIRECTION_KEEP_RIGHT_TO_TURN_90_DEG_LEFT = 30,
  DIRECTION_KEEP_LEFT_DRIVE_BACK_TO_TURN_90_DEG_RIGHT = 31,
  DIRECTION_KEEP_RIGHT_DRIVE_BACK_TO_TURN_90_DEG_LEFT = 32,
}

export enum osi3_DetectedTrafficSign_DetectedMainSign_Geometry {
  GEOMETRY_UNKNOWN = 0,
  GEOMETRY_OTHER = 1,
  GEOMETRY_CIRCLE = 2,
  GEOMETRY_TRIANGLE_TOP = 3,
  GEOMETRY_TRIANGLE_DOWN = 4,
  GEOMETRY_SQUARE = 5,
  GEOMETRY_POLE = 6,
  GEOMETRY_RECTANGLE = 7,
  GEOMETRY_PLATE = 8,
  GEOMETRY_DIAMOND = 9,
  GEOMETRY_ARROW_LEFT = 10,
  GEOMETRY_ARROW_RIGHT = 11,
  GEOMETRY_OCTAGON = 12,
}

export enum osi3_TrafficSign_MainSign_Classification_DirectionScope {
  DIRECTION_SCOPE_UNKNOWN = 0,
  DIRECTION_SCOPE_OTHER = 1,
  DIRECTION_SCOPE_NO_DIRECTION = 2,
  DIRECTION_SCOPE_LEFT = 3,
  DIRECTION_SCOPE_RIGHT = 4,
  DIRECTION_SCOPE_LEFT_RIGHT = 5,
}

export enum osi3_DetectedMovingObject_ReferencePoint {
  REFERENCE_POINT_UNKNOWN = 0,
  REFERENCE_POINT_OTHER = 1,
  REFERENCE_POINT_CENTER = 2,
  REFERENCE_POINT_MIDDLE_LEFT = 3,
  REFERENCE_POINT_MIDDLE_RIGHT = 4,
  REFERENCE_POINT_REAR_MIDDLE = 5,
  REFERENCE_POINT_REAR_LEFT = 6,
  REFERENCE_POINT_REAR_RIGHT = 7,
  REFERENCE_POINT_FRONT_MIDDLE = 8,
  REFERENCE_POINT_FRONT_LEFT = 9,
  REFERENCE_POINT_FRONT_RIGHT = 10,
}

export enum osi3_DetectedMovingObject_MovementState {
  MOVEMENT_STATE_UNKNOWN = 0,
  MOVEMENT_STATE_OTHER = 1,
  MOVEMENT_STATE_STATIONARY = 2,
  MOVEMENT_STATE_MOVING = 3,
  MOVEMENT_STATE_STOPPED = 4,
}

export enum osi3_UltrasonicSpecificObjectData_TrilaterationStatus {
  TRILATERATION_STATUS_UNKNOWN = 0,
  TRILATERATION_STATUS_OTHER = 1,
  TRILATERATION_STATUS_NOT_TRILATERATED = 2,
  TRILATERATION_STATUS_TRILATERATED = 3,
}

export enum osi3_UltrasonicSpecificObjectData_Trend {
  TREND_UNKNOWN = 0,
  TREND_OTHER = 1,
  TREND_CONSTANT_APPROACHING = 2,
  TREND_CONSTANT = 3,
  TREND_APPROACHING = 4,
  TREND_DEPARTING = 5,
}

export enum osi3_MovingObject_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_VEHICLE = 2,
  TYPE_PEDESTRIAN = 3,
  TYPE_ANIMAL = 4,
}

export enum osi3_MovingObject_VehicleClassification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_SMALL_CAR = 2,
  TYPE_COMPACT_CAR = 3,
  TYPE_CAR = 4,
  TYPE_MEDIUM_CAR = 4,
  TYPE_LUXURY_CAR = 5,
  TYPE_DELIVERY_VAN = 6,
  TYPE_VAN = 6,
  TYPE_HEAVY_TRUCK = 7,
  TYPE_SEMITRACTOR = 16,
  TYPE_SEMITRAILER = 8,
  TYPE_TRAILER = 9,
  TYPE_MOTORBIKE = 10,
  TYPE_MOTORCYCLE = 10,
  TYPE_BICYCLE = 11,
  TYPE_BUS = 12,
  TYPE_TRAM = 13,
  TYPE_TRAIN = 14,
  TYPE_WHEELCHAIR = 15,
  TYPE_STANDUP_SCOOTER = 17,
  TYPE_MICROMOBILITY_DEVICE = 18,
  TYPE_WORK_MACHINE = 19,
  TYPE_WATERCRAFT = 20,
  TYPE_AIRCRAFT = 21,
  TYPE_LAND_VEHICLE = 22,
}

export enum osi3_MovingObject_VehicleClassification_Role {
  ROLE_UNKNOWN = 0,
  ROLE_OTHER = 1,
  ROLE_CIVIL = 2,
  ROLE_AMBULANCE = 3,
  ROLE_FIRE = 4,
  ROLE_POLICE = 5,
  ROLE_PUBLIC_TRANSPORT = 6,
  ROLE_ROAD_ASSISTANCE = 7,
  ROLE_GARBAGE_COLLECTION = 8,
  ROLE_ROAD_CONSTRUCTION = 9,
  ROLE_MILITARY = 10,
}

export enum osi3_MovingObject_VehicleClassification_LightState_IndicatorState {
  INDICATOR_STATE_UNKNOWN = 0,
  INDICATOR_STATE_OTHER = 1,
  INDICATOR_STATE_OFF = 2,
  INDICATOR_STATE_LEFT = 3,
  INDICATOR_STATE_RIGHT = 4,
  INDICATOR_STATE_WARNING = 5,
}

export enum osi3_MovingObject_VehicleClassification_LightState_GenericLightState {
  GENERIC_LIGHT_STATE_UNKNOWN = 0,
  GENERIC_LIGHT_STATE_OTHER = 1,
  GENERIC_LIGHT_STATE_OFF = 2,
  GENERIC_LIGHT_STATE_ON = 3,
  GENERIC_LIGHT_STATE_FLASHING_BLUE = 4,
  GENERIC_LIGHT_STATE_FLASHING_BLUE_AND_RED = 5,
  GENERIC_LIGHT_STATE_FLASHING_AMBER = 6,
}

export enum osi3_MovingObject_VehicleClassification_LightState_BrakeLightState {
  BRAKE_LIGHT_STATE_UNKNOWN = 0,
  BRAKE_LIGHT_STATE_OTHER = 1,
  BRAKE_LIGHT_STATE_OFF = 2,
  BRAKE_LIGHT_STATE_NORMAL = 3,
  BRAKE_LIGHT_STATE_STRONG = 4,
}

export enum osi3_StationaryObject_Classification_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_BRIDGE = 2,
  TYPE_BUILDING = 3,
  TYPE_POLE = 4,
  TYPE_PYLON = 5,
  TYPE_DELINEATOR = 6,
  TYPE_TREE = 7,
  TYPE_BARRIER = 8,
  TYPE_VEGETATION = 9,
  TYPE_CURBSTONE = 10,
  TYPE_WALL = 11,
  TYPE_VERTICAL_STRUCTURE = 12,
  TYPE_RECTANGULAR_STRUCTURE = 13,
  TYPE_OVERHEAD_STRUCTURE = 14,
  TYPE_REFLECTIVE_STRUCTURE = 15,
  TYPE_CONSTRUCTION_SITE_ELEMENT = 16,
  TYPE_SPEED_BUMP = 17,
  TYPE_EMITTING_STRUCTURE = 18,
}

export enum osi3_StationaryObject_Classification_Material {
  MATERIAL_UNKNOWN = 0,
  MATERIAL_OTHER = 1,
  MATERIAL_WOOD = 2,
  MATERIAL_PLASTIC = 3,
  MATERIAL_CONCRETE = 4,
  MATERIAL_METAL = 5,
  MATERIAL_STONE = 6,
  MATERIAL_GLASS = 7,
  MATERIAL_GLAS = 7,
  MATERIAL_MUD = 8,
}

export enum osi3_StationaryObject_Classification_Density {
  DENSITY_UNKNOWN = 0,
  DENSITY_OTHER = 1,
  DENSITY_SOLID = 2,
  DENSITY_SMALL_MESH = 3,
  DENSITY_MEDIAN_MESH = 4,
  DENSITY_LARGE_MESH = 5,
  DENSITY_OPEN = 6,
}

export enum osi3_StationaryObject_Classification_Color {
  COLOR_UNKNOWN = 0,
  COLOR_OTHER = 1,
  COLOR_YELLOW = 2,
  COLOR_GREEN = 3,
  COLOR_BLUE = 4,
  COLOR_VIOLET = 5,
  COLOR_RED = 6,
  COLOR_ORANGE = 7,
  COLOR_BLACK = 8,
  COLOR_GRAY = 9,
  COLOR_GREY = 9,
  COLOR_WHITE = 10,
}

export enum osi3_CameraSensorViewConfiguration_ChannelFormat {
  CHANNEL_FORMAT_UNKNOWN = 0,
  CHANNEL_FORMAT_OTHER = 1,
  CHANNEL_FORMAT_MONO_U8_LIN = 2,
  CHANNEL_FORMAT_MONO_U16_LIN = 3,
  CHANNEL_FORMAT_MONO_U32_LIN = 4,
  CHANNEL_FORMAT_MONO_F32_LIN = 5,
  CHANNEL_FORMAT_RGB_U8_LIN = 6,
  CHANNEL_FORMAT_RGB_U16_LIN = 7,
  CHANNEL_FORMAT_RGB_U32_LIN = 8,
  CHANNEL_FORMAT_RGB_F32_LIN = 9,
  CHANNEL_FORMAT_BAYER_BGGR_U8_LIN = 10,
  CHANNEL_FORMAT_BAYER_BGGR_U16_LIN = 11,
  CHANNEL_FORMAT_BAYER_BGGR_U32_LIN = 12,
  CHANNEL_FORMAT_BAYER_BGGR_F32_LIN = 13,
  CHANNEL_FORMAT_BAYER_RGGB_U8_LIN = 14,
  CHANNEL_FORMAT_BAYER_RGGB_U16_LIN = 15,
  CHANNEL_FORMAT_BAYER_RGGB_U32_LIN = 16,
  CHANNEL_FORMAT_BAYER_RGGB_F32_LIN = 17,
  CHANNEL_FORMAT_RCCC_U8_LIN = 18,
  CHANNEL_FORMAT_RCCC_U16_LIN = 19,
  CHANNEL_FORMAT_RCCC_U32_LIN = 20,
  CHANNEL_FORMAT_RCCC_F32_LIN = 21,
  CHANNEL_FORMAT_RCCB_U8_LIN = 22,
  CHANNEL_FORMAT_RCCB_U16_LIN = 23,
  CHANNEL_FORMAT_RCCB_U32_LIN = 24,
  CHANNEL_FORMAT_RCCB_F32_LIN = 25,
}

export enum osi3_CameraSensorViewConfiguration_PixelOrder {
  PIXEL_ORDER_DEFAULT = 0,
  PIXEL_ORDER_OTHER = 1,
  PIXEL_ORDER_RIGHT_LEFT_TOP_BOTTOM = 2,
  PIXEL_ORDER_LEFT_RIGHT_BOTTOM_TOP = 3,
}

export enum osi3_LogicalLane_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_NORMAL = 2,
  TYPE_BIKING = 3,
  TYPE_SIDEWALK = 4,
  TYPE_PARKING = 5,
  TYPE_STOP = 6,
  TYPE_RESTRICTED = 7,
  TYPE_BORDER = 8,
  TYPE_SHOULDER = 9,
  TYPE_EXIT = 10,
  TYPE_ENTRY = 11,
  TYPE_ONRAMP = 12,
  TYPE_OFFRAMP = 13,
  TYPE_CONNECTINGRAMP = 14,
  TYPE_MEDIAN = 15,
  TYPE_CURB = 16,
  TYPE_RAIL = 17,
  TYPE_TRAM = 18,
}

export enum osi3_LogicalLane_MoveDirection {
  MOVE_DIRECTION_UNKNOWN = 0,
  MOVE_DIRECTION_OTHER = 1,
  MOVE_DIRECTION_INCREASING_S = 2,
  MOVE_DIRECTION_DECREASING_S = 3,
  MOVE_DIRECTION_BOTH_ALLOWED = 4,
}

export enum osi3_LogicalLane_RoadType {
  ROAD_TYPE_UNKNOWN = 0,
  ROAD_TYPE_OTHER = 1,
  ROAD_TYPE_LOWSPEED = 2,
  ROAD_TYPE_MOTORWAY = 3,
  ROAD_TYPE_PEDESTRIAN = 4,
  ROAD_TYPE_RURAL = 5,
  ROAD_TYPE_TOWNARTERIAL = 6,
  ROAD_TYPE_TOWNCOLLECTOR = 7,
  ROAD_TYPE_TOWNEXPRESSWAY = 8,
  ROAD_TYPE_TOWNLOCAL = 9,
  ROAD_TYPE_TOWNPLAYSTREET = 10,
  ROAD_TYPE_TOWNPRIVATE = 11,
  ROAD_TYPE_TOWN = 12,
  ROAD_TYPE_BICYCLE = 13,
}

export enum osi3_LogicalLane_TrafficRule_TrafficRuleType {
  TRAFFIC_RULE_TYPE_SPEED_LIMIT = 0,
}

export enum osi3_LogicalLaneBoundary_PassingRule {
  PASSING_RULE_UNKNOWN = 0,
  PASSING_RULE_OTHER = 1,
  PASSING_RULE_NONE_ALLOWED = 2,
  PASSING_RULE_INCREASING_T = 3,
  PASSING_RULE_DECREASING_T = 4,
  PASSING_RULE_BOTH_ALLOWED = 5,
}

export enum osi3_ReferenceLine_Type {
  TYPE_POLYLINE = 0,
  TYPE_POLYLINE_WITH_T_AXIS = 1,
}

export enum osi3_EnvironmentalConditions_AmbientIllumination {
  AMBIENT_ILLUMINATION_UNKNOWN = 0,
  AMBIENT_ILLUMINATION_OTHER = 1,
  AMBIENT_ILLUMINATION_LEVEL1 = 2,
  AMBIENT_ILLUMINATION_LEVEL2 = 3,
  AMBIENT_ILLUMINATION_LEVEL3 = 4,
  AMBIENT_ILLUMINATION_LEVEL4 = 5,
  AMBIENT_ILLUMINATION_LEVEL5 = 6,
  AMBIENT_ILLUMINATION_LEVEL6 = 7,
  AMBIENT_ILLUMINATION_LEVEL7 = 8,
  AMBIENT_ILLUMINATION_LEVEL8 = 9,
  AMBIENT_ILLUMINATION_LEVEL9 = 10,
}

export enum osi3_EnvironmentalConditions_Precipitation {
  PRECIPITATION_UNKNOWN = 0,
  PRECIPITATION_OTHER = 1,
  PRECIPITATION_NONE = 2,
  PRECIPITATION_VERY_LIGHT = 3,
  PRECIPITATION_LIGHT = 4,
  PRECIPITATION_MODERATE = 5,
  PRECIPITATION_HEAVY = 6,
  PRECIPITATION_VERY_HEAVY = 7,
  PRECIPITATION_EXTREME = 8,
}

export enum osi3_EnvironmentalConditions_Fog {
  FOG_UNKNOWN = 0,
  FOG_OTHER = 1,
  FOG_EXCELLENT_VISIBILITY = 2,
  FOG_GOOD_VISIBILITY = 3,
  FOG_MODERATE_VISIBILITY = 4,
  FOG_POOR_VISIBILITY = 5,
  FOG_MIST = 6,
  FOG_LIGHT = 7,
  FOG_THICK = 8,
  FOG_DENSE = 9,
}

export enum osi3_EnvironmentalConditions_CloudLayer_FractionalCloudCover {
  FRACTIONAL_CLOUD_COVER_UNKNOWN = 0,
  FRACTIONAL_CLOUD_COVER_OTHER = 1,
  FRACTIONAL_CLOUD_COVER_ZERO_OKTAS = 2,
  FRACTIONAL_CLOUD_COVER_ONE_OKTAS = 3,
  FRACTIONAL_CLOUD_COVER_TWO_OKTAS = 4,
  FRACTIONAL_CLOUD_COVER_THREE_OKTAS = 5,
  FRACTIONAL_CLOUD_COVER_FOUR_OKTAS = 6,
  FRACTIONAL_CLOUD_COVER_FIVE_OKTAS = 7,
  FRACTIONAL_CLOUD_COVER_SIX_OKTAS = 8,
  FRACTIONAL_CLOUD_COVER_SEVEN_OKTAS = 9,
  FRACTIONAL_CLOUD_COVER_EIGHT_OKTAS = 10,
  FRACTIONAL_CLOUD_COVER_SKY_OBSCURED = 11,
}

export enum osi3_MovingObject_PedestrianAttributes_Bone_Type {
  TYPE_ROOT = 0,
  TYPE_HIP = 1,
  TYPE_LOWER_SPINE = 2,
  TYPE_UPPER_SPINE = 3,
  TYPE_NECK = 4,
  TYPE_HEAD = 5,
  TYPE_SHOULDER_L = 6,
  TYPE_SHOULDER_R = 7,
  TYPE_UPPER_ARM_L = 8,
  TYPE_UPPER_ARM_R = 9,
  TYPE_LOWER_ARM_L = 10,
  TYPE_LOWER_ARM_R = 11,
  TYPE_FULL_HAND_L = 12,
  TYPE_FULL_HAND_R = 13,
  TYPE_UPPER_LEG_L = 14,
  TYPE_UPPER_LEG_R = 15,
  TYPE_LOWER_LEG_L = 16,
  TYPE_LOWER_LEG_R = 17,
  TYPE_FULL_FOOT_L = 18,
  TYPE_FULL_FOOT_R = 19,
}

export enum osi3_HostVehicleData_VehicleAutomatedDrivingFunction_Name {
  NAME_UNKNOWN = 0,
  NAME_OTHER = 1,
  NAME_BLIND_SPOT_WARNING = 2,
  NAME_FORWARD_COLLISION_WARNING = 3,
  NAME_LANE_DEPARTURE_WARNING = 4,
  NAME_PARKING_COLLISION_WARNING = 5,
  NAME_REAR_CROSS_TRAFFIC_WARNING = 6,
  NAME_AUTOMATIC_EMERGENCY_BRAKING = 7,
  NAME_AUTOMATIC_EMERGENCY_STEERING = 8,
  NAME_REVERSE_AUTOMATIC_EMERGENCY_BRAKING = 9,
  NAME_ADAPTIVE_CRUISE_CONTROL = 10,
  NAME_LANE_KEEPING_ASSIST = 11,
  NAME_ACTIVE_DRIVING_ASSISTANCE = 12,
  NAME_BACKUP_CAMERA = 13,
  NAME_SURROUND_VIEW_CAMERA = 14,
  NAME_ACTIVE_PARKING_ASSISTANCE = 15,
  NAME_REMOTE_PARKING_ASSISTANCE = 16,
  NAME_TRAILER_ASSISTANCE = 17,
  NAME_AUTOMATIC_HIGH_BEAMS = 18,
  NAME_DRIVER_MONITORING = 19,
  NAME_HEAD_UP_DISPLAY = 20,
  NAME_NIGHT_VISION = 21,
  NAME_URBAN_DRIVING = 22,
  NAME_HIGHWAY_AUTOPILOT = 23,
  NAME_CRUISE_CONTROL = 24,
  NAME_SPEED_LIMIT_CONTROL = 25,
}

export enum osi3_HostVehicleData_VehicleAutomatedDrivingFunction_State {
  STATE_UNKNOWN = 0,
  STATE_OTHER = 1,
  STATE_ERRORED = 2,
  STATE_UNAVAILABLE = 3,
  STATE_AVAILABLE = 4,
  STATE_STANDBY = 5,
  STATE_ACTIVE = 6,
}

export enum osi3_HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason {
  REASON_BRAKE_PEDAL = 0,
  REASON_STEERING_INPUT = 1,
}

export enum osi3_HostVehicleData_VehiclePowertrain_Motor_Type {
  TYPE_UNKNOWN = 0,
  TYPE_OTHER = 1,
  TYPE_OTTO = 2,
  TYPE_DIESEL = 3,
  TYPE_ELECTRIC = 4,
}

export enum osi3_HostVehicleData_VehicleBasics_OperatingState {
  OPERATING_STATE_UNKNOWN = 0,
  OPERATING_STATE_OTHER = 1,
  OPERATING_STATE_SLEEP = 2,
  OPERATING_STATE_STANDBY = 3,
  OPERATING_STATE_BOARDING = 4,
  OPERATING_STATE_ENTERTAINMENT = 5,
  OPERATING_STATE_DRIVING = 6,
  OPERATING_STATE_DIAGNOSTIC = 7,
}

export interface osi3_SensorData_Raw {
  version?: osi3_InterfaceVersion_Raw;
  timestamp?: osi3_Timestamp_Raw;
  host_vehicle_location?: osi3_BaseMoving_Raw;
  host_vehicle_location_rmse?: osi3_BaseMoving_Raw;
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  sensor_view?: osi3_SensorView_Raw[];
  last_measurement_time?: osi3_Timestamp_Raw;
  stationary_object_header?: osi3_DetectedEntityHeader_Raw;
  stationary_object?: osi3_DetectedStationaryObject_Raw[];
  moving_object_header?: osi3_DetectedEntityHeader_Raw;
  moving_object?: osi3_DetectedMovingObject_Raw[];
  traffic_sign_header?: osi3_DetectedEntityHeader_Raw;
  traffic_sign?: osi3_DetectedTrafficSign_Raw[];
  traffic_light_header?: osi3_DetectedEntityHeader_Raw;
  traffic_light?: osi3_DetectedTrafficLight_Raw[];
  road_marking_header?: osi3_DetectedEntityHeader_Raw;
  road_marking?: osi3_DetectedRoadMarking_Raw[];
  lane_boundary_header?: osi3_DetectedEntityHeader_Raw;
  lane_boundary?: osi3_DetectedLaneBoundary_Raw[];
  lane_header?: osi3_DetectedEntityHeader_Raw;
  lane?: osi3_DetectedLane_Raw[];
  occupant_header?: osi3_DetectedEntityHeader_Raw;
  occupant?: osi3_DetectedOccupant_Raw[];
  feature_data?: osi3_FeatureData_Raw;
  logical_detection_data?: osi3_LogicalDetectionData_Raw;
  virtual_detection_area?: osi3_SensorData_VirtualDetectionArea_Raw;
  system_time?: osi3_Timestamp_Raw;
}

export interface osi3_Timestamp_Raw {
  seconds?: LongLike;
  nanos?: number;
}

export interface osi3_SensorData_VirtualDetectionArea_Raw {
  polygon?: osi3_Polygon3d_Raw[];
}

export interface osi3_Polygon3d_Raw {
  vertex?: osi3_Vector3d_Raw[];
}

export interface osi3_Vector3d_Raw {
  x?: number;
  y?: number;
  z?: number;
}

export interface osi3_LogicalDetectionData_Raw {
  version?: osi3_InterfaceVersion_Raw;
  header?: osi3_LogicalDetectionDataHeader_Raw;
  logical_detection?: osi3_LogicalDetection_Raw[];
}

export interface osi3_LogicalDetection_Raw {
  existence_probability?: number;
  object_id?: osi3_Identifier_Raw;
  position?: osi3_Vector3d_Raw;
  position_rmse?: osi3_Vector3d_Raw;
  velocity?: osi3_Vector3d_Raw;
  velocity_rmse?: osi3_Vector3d_Raw;
  intensity?: number;
  snr?: number;
  point_target_probability?: number;
  sensor_id?: osi3_Identifier_Raw[];
  classification?: osi3_LogicalDetectionClassification;
  echo_pulse_width?: number;
}

export interface osi3_Identifier_Raw {
  value?: LongLike;
}

export interface osi3_LogicalDetectionDataHeader_Raw {
  logical_detection_time?: osi3_Timestamp_Raw;
  data_qualifier?: osi3_LogicalDetectionDataHeader_DataQualifier;
  number_of_valid_logical_detections?: number;
  sensor_id?: osi3_Identifier_Raw[];
}

export interface osi3_InterfaceVersion_Raw {
  version_major?: number;
  version_minor?: number;
  version_patch?: number;
}

export interface osi3_FeatureData_Raw {
  version?: osi3_InterfaceVersion_Raw;
  radar_sensor?: osi3_RadarDetectionData_Raw[];
  lidar_sensor?: osi3_LidarDetectionData_Raw[];
  ultrasonic_sensor?: osi3_UltrasonicDetectionData_Raw[];
  camera_sensor?: osi3_CameraDetectionData_Raw[];
}

export interface osi3_CameraDetectionData_Raw {
  header?: osi3_SensorDetectionHeader_Raw;
  specific_header?: osi3_CameraDetectionSpecificHeader_Raw;
  detection?: osi3_CameraDetection_Raw[];
  point?: osi3_CameraPoint_Raw[];
}

export interface osi3_CameraPoint_Raw {
  existence_probability?: number;
  point?: osi3_Spherical3d_Raw;
  point_rmse?: osi3_Spherical3d_Raw;
}

export interface osi3_Spherical3d_Raw {
  distance?: number;
  azimuth?: number;
  elevation?: number;
}

export interface osi3_CameraDetection_Raw {
  existence_probability?: number;
  object_id?: osi3_Identifier_Raw;
  time_difference?: osi3_Timestamp_Raw;
  image_shape_type?: osi3_CameraDetection_ImageShapeType;
  shape_classification_background?: boolean;
  shape_classification_foreground?: boolean;
  shape_classification_flat?: boolean;
  shape_classification_upright?: boolean;
  shape_classification_ground?: boolean;
  shape_classification_sky?: boolean;
  shape_classification_vegetation?: boolean;
  shape_classification_road?: boolean;
  shape_classification_non_driving_lane?: boolean;
  shape_classification_non_road?: boolean;
  shape_classification_stationary_object?: boolean;
  shape_classification_moving_object?: boolean;
  shape_classification_landmark?: boolean;
  shape_classification_traffic_sign?: boolean;
  shape_classification_traffic_light?: boolean;
  shape_classification_road_marking?: boolean;
  shape_classification_vehicle?: boolean;
  shape_classification_pedestrian?: boolean;
  shape_classification_animal?: boolean;
  shape_classification_pedestrian_front?: boolean;
  shape_classification_pedestrian_side?: boolean;
  shape_classification_pedestrian_rear?: boolean;
  shape_classification_probability?: number;
  color?: osi3_CameraDetection_Color;
  color_probability?: number;
  ambiguity_id?: osi3_Identifier_Raw;
  first_point_index?: number;
  number_of_points?: number;
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_ColorDescription_Raw {
  grey?: osi3_ColorGrey_Raw;
  rgb?: osi3_ColorRGB_Raw;
  rgbir?: osi3_ColorRGBIR_Raw;
  hsv?: osi3_ColorHSV_Raw;
  luv?: osi3_ColorLUV_Raw;
  cmyk?: osi3_ColorCMYK_Raw;
}

export interface osi3_ColorCMYK_Raw {
  cyan?: number;
  magenta?: number;
  yellow?: number;
  key?: number;
}

export interface osi3_ColorLUV_Raw {
  luminance?: number;
  u?: number;
  v?: number;
}

export interface osi3_ColorHSV_Raw {
  hue?: number;
  saturation?: number;
  value?: number;
}

export interface osi3_ColorRGBIR_Raw {
  red?: number;
  green?: number;
  blue?: number;
  infrared?: number;
}

export interface osi3_ColorRGB_Raw {
  red?: number;
  green?: number;
  blue?: number;
}

export interface osi3_ColorGrey_Raw {
  grey?: number;
}

export interface osi3_CameraDetectionSpecificHeader_Raw {
  number_of_valid_points?: number;
}

export interface osi3_SensorDetectionHeader_Raw {
  measurement_time?: osi3_Timestamp_Raw;
  cycle_counter?: LongLike;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  data_qualifier?: osi3_SensorDetectionHeader_DataQualifier;
  number_of_valid_detections?: number;
  sensor_id?: osi3_Identifier_Raw;
  extended_qualifier?: osi3_SensorDetectionHeader_ExtendedQualifier;
}

export interface osi3_MountingPosition_Raw {
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
}

export interface osi3_Orientation3d_Raw {
  roll?: number;
  pitch?: number;
  yaw?: number;
}

export interface osi3_UltrasonicDetectionData_Raw {
  header?: osi3_SensorDetectionHeader_Raw;
  specific_header?: osi3_UltrasonicDetectionSpecificHeader_Raw;
  detection?: osi3_UltrasonicDetection_Raw[];
  indirect_detection?: osi3_UltrasonicIndirectDetection_Raw[];
}

export interface osi3_UltrasonicIndirectDetection_Raw {
  existence_probability?: number;
  object_id?: osi3_Identifier_Raw;
  ellipsoid_radial?: number;
  ellipsoid_axial?: number;
  receiver_id?: osi3_Identifier_Raw;
  receiver_origin?: osi3_Vector3d_Raw;
}

export interface osi3_UltrasonicDetection_Raw {
  existence_probability?: number;
  object_id?: osi3_Identifier_Raw;
  distance?: number;
}

export interface osi3_UltrasonicDetectionSpecificHeader_Raw {
  max_range?: number;
  number_of_valid_indirect_detections?: number;
}

export interface osi3_LidarDetectionData_Raw {
  header?: osi3_SensorDetectionHeader_Raw;
  detection?: osi3_LidarDetection_Raw[];
}

export interface osi3_LidarDetection_Raw {
  existence_probability?: number;
  object_id?: osi3_Identifier_Raw;
  position?: osi3_Spherical3d_Raw;
  position_rmse?: osi3_Spherical3d_Raw;
  height?: number;
  height_rmse?: number;
  intensity?: number;
  free_space_probability?: number;
  classification?: osi3_DetectionClassification;
  reflectivity?: number;
  echo_pulse_width?: number;
  radial_velocity?: number;
  beam_id?: osi3_Identifier_Raw;
}

export interface osi3_RadarDetectionData_Raw {
  header?: osi3_SensorDetectionHeader_Raw;
  detection?: osi3_RadarDetection_Raw[];
}

export interface osi3_RadarDetection_Raw {
  existence_probability?: number;
  object_id?: osi3_Identifier_Raw;
  position?: osi3_Spherical3d_Raw;
  position_rmse?: osi3_Spherical3d_Raw;
  radial_velocity?: number;
  radial_velocity_rmse?: number;
  rcs?: number;
  snr?: number;
  point_target_probability?: number;
  ambiguity_id?: osi3_Identifier_Raw;
  classification?: osi3_DetectionClassification;
}

export interface osi3_DetectedOccupant_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  candidate?: osi3_DetectedOccupant_CandidateOccupant_Raw[];
}

export interface osi3_DetectedOccupant_CandidateOccupant_Raw {
  probability?: number;
  classification?: osi3_Occupant_Classification_Raw;
}

export interface osi3_Occupant_Classification_Raw {
  is_driver?: boolean;
  seat?: osi3_Occupant_Classification_Seat;
  steering_control?: osi3_Occupant_Classification_SteeringControl;
}

export interface osi3_DetectedItemHeader_Raw {
  tracking_id?: osi3_Identifier_Raw;
  ground_truth_id?: osi3_Identifier_Raw[];
  existence_probability?: number;
  age?: number;
  measurement_state?: osi3_DetectedItemHeader_MeasurementState;
  sensor_id?: osi3_Identifier_Raw[];
}

export interface osi3_DetectedEntityHeader_Raw {
  measurement_time?: osi3_Timestamp_Raw;
  cycle_counter?: LongLike;
  data_qualifier?: osi3_DetectedEntityHeader_DataQualifier;
}

export interface osi3_DetectedLane_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  candidate?: osi3_DetectedLane_CandidateLane_Raw[];
}

export interface osi3_DetectedLane_CandidateLane_Raw {
  probability?: number;
  classification?: osi3_Lane_Classification_Raw;
}

export interface osi3_Lane_Classification_Raw {
  type?: osi3_Lane_Classification_Type;
  is_host_vehicle_lane?: boolean;
  centerline?: osi3_Vector3d_Raw[];
  centerline_is_driving_direction?: boolean;
  left_adjacent_lane_id?: osi3_Identifier_Raw[];
  right_adjacent_lane_id?: osi3_Identifier_Raw[];
  lane_pairing?: osi3_Lane_Classification_LanePairing_Raw[];
  right_lane_boundary_id?: osi3_Identifier_Raw[];
  left_lane_boundary_id?: osi3_Identifier_Raw[];
  free_lane_boundary_id?: osi3_Identifier_Raw[];
  road_condition?: osi3_Lane_Classification_RoadCondition_Raw;
  subtype?: osi3_Lane_Classification_Subtype;
}

export interface osi3_Lane_Classification_RoadCondition_Raw {
  surface_temperature?: number;
  surface_water_film?: number;
  surface_freezing_point?: number;
  surface_ice?: number;
  surface_roughness?: number;
  surface_texture?: number;
}

export interface osi3_Lane_Classification_LanePairing_Raw {
  antecessor_lane_id?: osi3_Identifier_Raw;
  successor_lane_id?: osi3_Identifier_Raw;
}

export interface osi3_DetectedLaneBoundary_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  candidate?: osi3_DetectedLaneBoundary_CandidateLaneBoundary_Raw[];
  boundary_line?: osi3_LaneBoundary_BoundaryPoint_Raw[];
  boundary_line_rmse?: osi3_LaneBoundary_BoundaryPoint_Raw[];
  boundary_line_confidences?: number[];
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_LaneBoundary_BoundaryPoint_Raw {
  position?: osi3_Vector3d_Raw;
  width?: number;
  height?: number;
  dash?: osi3_LaneBoundary_BoundaryPoint_Dash;
}

export interface osi3_DetectedLaneBoundary_CandidateLaneBoundary_Raw {
  probability?: number;
  classification?: osi3_LaneBoundary_Classification_Raw;
}

export interface osi3_LaneBoundary_Classification_Raw {
  type?: osi3_LaneBoundary_Classification_Type;
  color?: osi3_LaneBoundary_Classification_Color;
  limiting_structure_id?: osi3_Identifier_Raw[];
}

export interface osi3_DetectedRoadMarking_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  base?: osi3_BaseStationary_Raw;
  base_rmse?: osi3_BaseStationary_Raw;
  candidate?: osi3_DetectedRoadMarking_CandidateRoadMarking_Raw[];
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_DetectedRoadMarking_CandidateRoadMarking_Raw {
  probability?: number;
  classification?: osi3_RoadMarking_Classification_Raw;
}

export interface osi3_RoadMarking_Classification_Raw {
  type?: osi3_RoadMarking_Classification_Type;
  traffic_main_sign_type?: osi3_TrafficSign_MainSign_Classification_Type;
  monochrome_color?: osi3_RoadMarking_Classification_Color;
  value?: osi3_TrafficSignValue_Raw;
  value_text?: string;
  assigned_lane_id?: osi3_Identifier_Raw[];
  is_out_of_service?: boolean;
  country?: string;
  country_revision?: string;
  code?: string;
  sub_code?: string;
  logical_lane_assignment?: osi3_LogicalLaneAssignment_Raw[];
}

export interface osi3_LogicalLaneAssignment_Raw {
  assigned_lane_id?: osi3_Identifier_Raw;
  s_position?: number;
  t_position?: number;
  angle_to_lane?: number;
}

export interface osi3_TrafficSignValue_Raw {
  value?: number;
  value_unit?: osi3_TrafficSignValue_Unit;
  text?: string;
}

export interface osi3_BaseStationary_Raw {
  dimension?: osi3_Dimension3d_Raw;
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
  base_polygon?: osi3_Vector2d_Raw[];
  bounding_box_section?: osi3_BoundingBox_Raw[];
}

export interface osi3_BoundingBox_Raw {
  dimension?: osi3_Dimension3d_Raw;
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
  contained_object_type?: osi3_BoundingBox_Type;
  model_reference?: string;
}

export interface osi3_Dimension3d_Raw {
  length?: number;
  width?: number;
  height?: number;
}

export interface osi3_Vector2d_Raw {
  x?: number;
  y?: number;
}

export interface osi3_DetectedTrafficLight_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  base?: osi3_BaseStationary_Raw;
  base_rmse?: osi3_BaseStationary_Raw;
  candidate?: osi3_DetectedTrafficLight_CandidateTrafficLight_Raw[];
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_DetectedTrafficLight_CandidateTrafficLight_Raw {
  probability?: number;
  classification?: osi3_TrafficLight_Classification_Raw;
}

export interface osi3_TrafficLight_Classification_Raw {
  color?: osi3_TrafficLight_Classification_Color;
  icon?: osi3_TrafficLight_Classification_Icon;
  mode?: osi3_TrafficLight_Classification_Mode;
  counter?: number;
  assigned_lane_id?: osi3_Identifier_Raw[];
  is_out_of_service?: boolean;
  logical_lane_assignment?: osi3_LogicalLaneAssignment_Raw[];
}

export interface osi3_DetectedTrafficSign_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  main_sign?: osi3_DetectedTrafficSign_DetectedMainSign_Raw;
  supplementary_sign?: osi3_DetectedTrafficSign_DetectedSupplementarySign_Raw[];
}

export interface osi3_DetectedTrafficSign_DetectedSupplementarySign_Raw {
  candidate?: osi3_DetectedTrafficSign_DetectedSupplementarySign_CandidateSupplementarySign_Raw[];
  base?: osi3_BaseStationary_Raw;
  base_rmse?: osi3_BaseStationary_Raw;
}

export interface osi3_DetectedTrafficSign_DetectedSupplementarySign_CandidateSupplementarySign_Raw {
  probability?: number;
  classification?: osi3_TrafficSign_SupplementarySign_Classification_Raw;
}

export interface osi3_TrafficSign_SupplementarySign_Classification_Raw {
  variability?: osi3_TrafficSign_Variability;
  type?: osi3_TrafficSign_SupplementarySign_Classification_Type;
  value?: osi3_TrafficSignValue_Raw[];
  assigned_lane_id?: osi3_Identifier_Raw[];
  actor?: osi3_TrafficSign_SupplementarySign_Classification_Actor[];
  arrow?: osi3_TrafficSign_SupplementarySign_Classification_Arrow_Raw[];
  is_out_of_service?: boolean;
  country?: string;
  country_revision?: string;
  code?: string;
  sub_code?: string;
  logical_lane_assignment?: osi3_LogicalLaneAssignment_Raw[];
}

export interface osi3_TrafficSign_SupplementarySign_Classification_Arrow_Raw {
  lane_id?: osi3_Identifier_Raw[];
  direction?: osi3_TrafficSign_SupplementarySign_Classification_Arrow_Direction[];
}

export interface osi3_DetectedTrafficSign_DetectedMainSign_Raw {
  candidate?: osi3_DetectedTrafficSign_DetectedMainSign_CandidateMainSign_Raw[];
  base?: osi3_BaseStationary_Raw;
  base_rmse?: osi3_BaseStationary_Raw;
  geometry?: osi3_DetectedTrafficSign_DetectedMainSign_Geometry;
}

export interface osi3_DetectedTrafficSign_DetectedMainSign_CandidateMainSign_Raw {
  probability?: number;
  classification?: osi3_TrafficSign_MainSign_Classification_Raw;
}

export interface osi3_TrafficSign_MainSign_Classification_Raw {
  variability?: osi3_TrafficSign_Variability;
  type?: osi3_TrafficSign_MainSign_Classification_Type;
  value?: osi3_TrafficSignValue_Raw;
  direction_scope?: osi3_TrafficSign_MainSign_Classification_DirectionScope;
  assigned_lane_id?: osi3_Identifier_Raw[];
  vertically_mirrored?: boolean;
  is_out_of_service?: boolean;
  country?: string;
  country_revision?: string;
  code?: string;
  sub_code?: string;
  logical_lane_assignment?: osi3_LogicalLaneAssignment_Raw[];
}

export interface osi3_DetectedMovingObject_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  base?: osi3_BaseMoving_Raw;
  base_rmse?: osi3_BaseMoving_Raw;
  reference_point?: osi3_DetectedMovingObject_ReferencePoint;
  movement_state?: osi3_DetectedMovingObject_MovementState;
  percentage_side_lane_left?: number;
  percentage_side_lane_right?: number;
  candidate?: osi3_DetectedMovingObject_CandidateMovingObject_Raw[];
  color_description?: osi3_ColorDescription_Raw;
  radar_specifics?: osi3_RadarSpecificObjectData_Raw;
  lidar_specifics?: osi3_LidarSpecificObjectData_Raw;
  camera_specifics?: osi3_CameraSpecificObjectData_Raw;
  ultrasonic_specifics?: osi3_UltrasonicSpecificObjectData_Raw;
}

export interface osi3_UltrasonicSpecificObjectData_Raw {
  maximum_measurement_distance_sensor?: number;
  probability?: number;
  trilateration_status?: osi3_UltrasonicSpecificObjectData_TrilaterationStatus;
  trend?: osi3_UltrasonicSpecificObjectData_Trend;
  signalway?: osi3_UltrasonicSpecificObjectData_Signalway_Raw[];
}

export interface osi3_UltrasonicSpecificObjectData_Signalway_Raw {
  sender_id?: osi3_Identifier_Raw;
  receiver_id?: osi3_Identifier_Raw;
}

export interface osi3_CameraSpecificObjectData_Raw {
}

export interface osi3_LidarSpecificObjectData_Raw {
}

export interface osi3_RadarSpecificObjectData_Raw {
  rcs?: number;
}

export interface osi3_DetectedMovingObject_CandidateMovingObject_Raw {
  probability?: number;
  type?: osi3_MovingObject_Type;
  vehicle_classification?: osi3_MovingObject_VehicleClassification_Raw;
  head_pose?: osi3_Orientation3d_Raw;
  upper_body_pose?: osi3_Orientation3d_Raw;
  moving_object_classification?: osi3_MovingObject_MovingObjectClassification_Raw;
}

export interface osi3_MovingObject_MovingObjectClassification_Raw {
  assigned_lane_id?: osi3_Identifier_Raw[];
  assigned_lane_percentage?: number[];
  logical_lane_assignment?: osi3_LogicalLaneAssignment_Raw[];
}

export interface osi3_MovingObject_VehicleClassification_Raw {
  type?: osi3_MovingObject_VehicleClassification_Type;
  light_state?: osi3_MovingObject_VehicleClassification_LightState_Raw;
  has_trailer?: boolean;
  trailer_id?: osi3_Identifier_Raw;
  role?: osi3_MovingObject_VehicleClassification_Role;
}

export interface osi3_MovingObject_VehicleClassification_LightState_Raw {
  indicator_state?: osi3_MovingObject_VehicleClassification_LightState_IndicatorState;
  front_fog_light?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  rear_fog_light?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  head_light?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  high_beam?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  reversing_light?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  tail_light?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  brake_light_state?: osi3_MovingObject_VehicleClassification_LightState_BrakeLightState;
  license_plate_illumination_rear?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  emergency_vehicle_illumination?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
  service_vehicle_illumination?: osi3_MovingObject_VehicleClassification_LightState_GenericLightState;
}

export interface osi3_BaseMoving_Raw {
  dimension?: osi3_Dimension3d_Raw;
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
  velocity?: osi3_Vector3d_Raw;
  acceleration?: osi3_Vector3d_Raw;
  orientation_rate?: osi3_Orientation3d_Raw;
  orientation_acceleration?: osi3_Orientation3d_Raw;
  base_polygon?: osi3_Vector2d_Raw[];
  bounding_box_section?: osi3_BoundingBox_Raw[];
}

export interface osi3_DetectedStationaryObject_Raw {
  header?: osi3_DetectedItemHeader_Raw;
  base?: osi3_BaseStationary_Raw;
  base_rmse?: osi3_BaseStationary_Raw;
  candidate?: osi3_DetectedStationaryObject_CandidateStationaryObject_Raw[];
  color_description?: osi3_ColorDescription_Raw;
  radar_specifics?: osi3_RadarSpecificObjectData_Raw;
  lidar_specifics?: osi3_LidarSpecificObjectData_Raw;
  camera_specifics?: osi3_CameraSpecificObjectData_Raw;
  ultrasonic_specifics?: osi3_UltrasonicSpecificObjectData_Raw;
}

export interface osi3_DetectedStationaryObject_CandidateStationaryObject_Raw {
  probability?: number;
  classification?: osi3_StationaryObject_Classification_Raw;
}

export interface osi3_StationaryObject_Classification_Raw {
  type?: osi3_StationaryObject_Classification_Type;
  material?: osi3_StationaryObject_Classification_Material;
  density?: osi3_StationaryObject_Classification_Density;
  color?: osi3_StationaryObject_Classification_Color;
  emitting_structure_attribute?: osi3_StationaryObject_Classification_EmittingStructureAttribute_Raw;
  assigned_lane_id?: osi3_Identifier_Raw[];
  assigned_lane_percentage?: number[];
  logical_lane_assignment?: osi3_LogicalLaneAssignment_Raw[];
}

export interface osi3_StationaryObject_Classification_EmittingStructureAttribute_Raw {
  wavelength_data?: osi3_WavelengthData_Raw[];
  emitted_spatial_signal_strength?: osi3_SpatialSignalStrength_Raw[];
}

export interface osi3_SpatialSignalStrength_Raw {
  horizontal_angle?: number;
  vertical_angle?: number;
  signal_strength?: number;
}

export interface osi3_WavelengthData_Raw {
  start?: number;
  end?: number;
  samples_number?: number;
}

export interface osi3_SensorView_Raw {
  version?: osi3_InterfaceVersion_Raw;
  timestamp?: osi3_Timestamp_Raw;
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  host_vehicle_data?: osi3_HostVehicleData_Raw;
  global_ground_truth?: osi3_GroundTruth_Raw;
  host_vehicle_id?: osi3_Identifier_Raw;
  generic_sensor_view?: osi3_GenericSensorView_Raw[];
  radar_sensor_view?: osi3_RadarSensorView_Raw[];
  lidar_sensor_view?: osi3_LidarSensorView_Raw[];
  camera_sensor_view?: osi3_CameraSensorView_Raw[];
  ultrasonic_sensor_view?: osi3_UltrasonicSensorView_Raw[];
}

export interface osi3_UltrasonicSensorView_Raw {
  view_configuration?: osi3_UltrasonicSensorViewConfiguration_Raw;
}

export interface osi3_UltrasonicSensorViewConfiguration_Raw {
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  field_of_view_horizontal?: number;
  field_of_view_vertical?: number;
}

export interface osi3_CameraSensorView_Raw {
  view_configuration?: osi3_CameraSensorViewConfiguration_Raw;
  image_data?: Uint8Array;
}

export interface osi3_CameraSensorViewConfiguration_Raw {
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  field_of_view_horizontal?: number;
  field_of_view_vertical?: number;
  number_of_pixels_horizontal?: number;
  number_of_pixels_vertical?: number;
  channel_format?: osi3_CameraSensorViewConfiguration_ChannelFormat[];
  samples_per_pixel?: number;
  max_number_of_interactions?: number;
  wavelength_data?: osi3_WavelengthData_Raw[];
  pixel_order?: osi3_CameraSensorViewConfiguration_PixelOrder;
}

export interface osi3_LidarSensorView_Raw {
  view_configuration?: osi3_LidarSensorViewConfiguration_Raw;
  reflection?: osi3_LidarSensorView_Reflection_Raw[];
}

export interface osi3_LidarSensorView_Reflection_Raw {
  signal_strength?: number;
  time_of_flight?: number;
  doppler_shift?: number;
  normal_to_surface?: osi3_Vector3d_Raw;
  object_id?: osi3_Identifier_Raw;
}

export interface osi3_LidarSensorViewConfiguration_Raw {
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  field_of_view_horizontal?: number;
  field_of_view_vertical?: number;
  number_of_rays_horizontal?: number;
  number_of_rays_vertical?: number;
  max_number_of_interactions?: number;
  emitter_frequency?: number;
  num_of_pixels?: number;
  directions?: osi3_Vector3d_Raw[];
  timings?: number[];
}

export interface osi3_RadarSensorView_Raw {
  view_configuration?: osi3_RadarSensorViewConfiguration_Raw;
  reflection?: osi3_RadarSensorView_Reflection_Raw[];
}

export interface osi3_RadarSensorView_Reflection_Raw {
  signal_strength?: number;
  time_of_flight?: number;
  doppler_shift?: number;
  source_horizontal_angle?: number;
  source_vertical_angle?: number;
}

export interface osi3_RadarSensorViewConfiguration_Raw {
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  field_of_view_horizontal?: number;
  field_of_view_vertical?: number;
  number_of_rays_horizontal?: number;
  number_of_rays_vertical?: number;
  max_number_of_interactions?: number;
  emitter_frequency?: number;
  tx_antenna_diagram?: osi3_RadarSensorViewConfiguration_AntennaDiagramEntry_Raw[];
  rx_antenna_diagram?: osi3_RadarSensorViewConfiguration_AntennaDiagramEntry_Raw[];
}

export interface osi3_RadarSensorViewConfiguration_AntennaDiagramEntry_Raw {
  horizontal_angle?: number;
  vertical_angle?: number;
  response?: number;
}

export interface osi3_GenericSensorView_Raw {
  view_configuration?: osi3_GenericSensorViewConfiguration_Raw;
}

export interface osi3_GenericSensorViewConfiguration_Raw {
  sensor_id?: osi3_Identifier_Raw;
  mounting_position?: osi3_MountingPosition_Raw;
  mounting_position_rmse?: osi3_MountingPosition_Raw;
  field_of_view_horizontal?: number;
  field_of_view_vertical?: number;
}

export interface osi3_GroundTruth_Raw {
  version?: osi3_InterfaceVersion_Raw;
  timestamp?: osi3_Timestamp_Raw;
  host_vehicle_id?: osi3_Identifier_Raw;
  stationary_object?: osi3_StationaryObject_Raw[];
  moving_object?: osi3_MovingObject_Raw[];
  traffic_sign?: osi3_TrafficSign_Raw[];
  traffic_light?: osi3_TrafficLight_Raw[];
  road_marking?: osi3_RoadMarking_Raw[];
  lane_boundary?: osi3_LaneBoundary_Raw[];
  lane?: osi3_Lane_Raw[];
  occupant?: osi3_Occupant_Raw[];
  environmental_conditions?: osi3_EnvironmentalConditions_Raw;
  country_code?: number;
  proj_string?: string;
  map_reference?: string;
  model_reference?: string;
  reference_line?: osi3_ReferenceLine_Raw[];
  logical_lane_boundary?: osi3_LogicalLaneBoundary_Raw[];
  logical_lane?: osi3_LogicalLane_Raw[];
  proj_frame_offset?: osi3_GroundTruth_ProjFrameOffset_Raw;
}

export interface osi3_GroundTruth_ProjFrameOffset_Raw {
  position?: osi3_Vector3d_Raw;
  yaw?: number;
}

export interface osi3_LogicalLane_Raw {
  id?: osi3_Identifier_Raw;
  type?: osi3_LogicalLane_Type;
  source_reference?: osi3_ExternalReference_Raw[];
  physical_lane_reference?: osi3_LogicalLane_PhysicalLaneReference_Raw[];
  reference_line_id?: osi3_Identifier_Raw;
  start_s?: number;
  end_s?: number;
  move_direction?: osi3_LogicalLane_MoveDirection;
  right_adjacent_lane?: osi3_LogicalLane_LaneRelation_Raw[];
  left_adjacent_lane?: osi3_LogicalLane_LaneRelation_Raw[];
  overlapping_lane?: osi3_LogicalLane_LaneRelation_Raw[];
  right_boundary_id?: osi3_Identifier_Raw[];
  left_boundary_id?: osi3_Identifier_Raw[];
  predecessor_lane?: osi3_LogicalLane_LaneConnection_Raw[];
  successor_lane?: osi3_LogicalLane_LaneConnection_Raw[];
  street_name?: string;
  traffic_rule?: osi3_LogicalLane_TrafficRule_Raw[];
  road_type?: osi3_LogicalLane_RoadType;
}

export interface osi3_LogicalLane_TrafficRule_Raw {
  traffic_rule_type?: osi3_LogicalLane_TrafficRule_TrafficRuleType;
  traffic_rule_validity?: osi3_LogicalLane_TrafficRule_TrafficRuleValidity_Raw;
  speed_limit?: osi3_LogicalLane_TrafficRule_SpeedLimit_Raw;
}

export interface osi3_LogicalLane_TrafficRule_SpeedLimit_Raw {
  speed_limit_value?: osi3_TrafficSignValue_Raw;
}

export interface osi3_LogicalLane_TrafficRule_TrafficRuleValidity_Raw {
  start_s?: number;
  end_s?: number;
  valid_for_type?: osi3_LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity_Raw[];
}

export interface osi3_LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity_Raw {
  type?: osi3_MovingObject_Type;
  vehicle_type?: osi3_MovingObject_VehicleClassification_Type;
  vehicle_role?: osi3_MovingObject_VehicleClassification_Role;
}

export interface osi3_LogicalLane_LaneConnection_Raw {
  other_lane_id?: osi3_Identifier_Raw;
  at_begin_of_other_lane?: boolean;
}

export interface osi3_LogicalLane_LaneRelation_Raw {
  other_lane_id?: osi3_Identifier_Raw;
  start_s?: number;
  end_s?: number;
  start_s_other?: number;
  end_s_other?: number;
}

export interface osi3_LogicalLane_PhysicalLaneReference_Raw {
  physical_lane_id?: osi3_Identifier_Raw;
  start_s?: number;
  end_s?: number;
}

export interface osi3_ExternalReference_Raw {
  reference?: string;
  type?: string;
  identifier?: string[];
}

export interface osi3_LogicalLaneBoundary_Raw {
  id?: osi3_Identifier_Raw;
  boundary_line?: osi3_LogicalLaneBoundary_LogicalBoundaryPoint_Raw[];
  reference_line_id?: osi3_Identifier_Raw;
  physical_boundary_id?: osi3_Identifier_Raw[];
  passing_rule?: osi3_LogicalLaneBoundary_PassingRule;
  source_reference?: osi3_ExternalReference_Raw[];
}

export interface osi3_LogicalLaneBoundary_LogicalBoundaryPoint_Raw {
  position?: osi3_Vector3d_Raw;
  s_position?: number;
  t_position?: number;
}

export interface osi3_ReferenceLine_Raw {
  id?: osi3_Identifier_Raw;
  type?: osi3_ReferenceLine_Type;
  poly_line?: osi3_ReferenceLine_ReferenceLinePoint_Raw[];
}

export interface osi3_ReferenceLine_ReferenceLinePoint_Raw {
  world_position?: osi3_Vector3d_Raw;
  s_position?: number;
  t_axis_yaw?: number;
}

export interface osi3_EnvironmentalConditions_Raw {
  ambient_illumination?: osi3_EnvironmentalConditions_AmbientIllumination;
  time_of_day?: osi3_EnvironmentalConditions_TimeOfDay_Raw;
  unix_timestamp?: LongLike;
  atmospheric_pressure?: number;
  temperature?: number;
  relative_humidity?: number;
  precipitation?: osi3_EnvironmentalConditions_Precipitation;
  fog?: osi3_EnvironmentalConditions_Fog;
  source_reference?: osi3_ExternalReference_Raw[];
  clouds?: osi3_EnvironmentalConditions_CloudLayer_Raw;
  wind?: osi3_EnvironmentalConditions_Wind_Raw;
  sun?: osi3_EnvironmentalConditions_Sun_Raw;
}

export interface osi3_EnvironmentalConditions_Sun_Raw {
  azimuth?: number;
  elevation?: number;
  intensity?: number;
}

export interface osi3_EnvironmentalConditions_Wind_Raw {
  origin_direction?: number;
  speed?: number;
}

export interface osi3_EnvironmentalConditions_CloudLayer_Raw {
  fractional_cloud_cover?: osi3_EnvironmentalConditions_CloudLayer_FractionalCloudCover;
}

export interface osi3_EnvironmentalConditions_TimeOfDay_Raw {
  seconds_since_midnight?: number;
}

export interface osi3_Occupant_Raw {
  id?: osi3_Identifier_Raw;
  classification?: osi3_Occupant_Classification_Raw;
  source_reference?: osi3_ExternalReference_Raw[];
}

export interface osi3_Lane_Raw {
  id?: osi3_Identifier_Raw;
  classification?: osi3_Lane_Classification_Raw;
  source_reference?: osi3_ExternalReference_Raw[];
}

export interface osi3_LaneBoundary_Raw {
  id?: osi3_Identifier_Raw;
  boundary_line?: osi3_LaneBoundary_BoundaryPoint_Raw[];
  classification?: osi3_LaneBoundary_Classification_Raw;
  source_reference?: osi3_ExternalReference_Raw[];
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_RoadMarking_Raw {
  id?: osi3_Identifier_Raw;
  base?: osi3_BaseStationary_Raw;
  classification?: osi3_RoadMarking_Classification_Raw;
  source_reference?: osi3_ExternalReference_Raw[];
  color_description?: osi3_ColorDescription_Raw;
  model_reference?: string;
}

export interface osi3_TrafficLight_Raw {
  id?: osi3_Identifier_Raw;
  base?: osi3_BaseStationary_Raw;
  classification?: osi3_TrafficLight_Classification_Raw;
  model_reference?: string;
  source_reference?: osi3_ExternalReference_Raw[];
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_TrafficSign_Raw {
  id?: osi3_Identifier_Raw;
  main_sign?: osi3_TrafficSign_MainSign_Raw;
  supplementary_sign?: osi3_TrafficSign_SupplementarySign_Raw[];
  source_reference?: osi3_ExternalReference_Raw[];
}

export interface osi3_TrafficSign_SupplementarySign_Raw {
  base?: osi3_BaseStationary_Raw;
  classification?: osi3_TrafficSign_SupplementarySign_Classification_Raw;
  model_reference?: string;
}

export interface osi3_TrafficSign_MainSign_Raw {
  base?: osi3_BaseStationary_Raw;
  classification?: osi3_TrafficSign_MainSign_Classification_Raw;
  model_reference?: string;
}

export interface osi3_MovingObject_Raw {
  id?: osi3_Identifier_Raw;
  base?: osi3_BaseMoving_Raw;
  type?: osi3_MovingObject_Type;
  assigned_lane_id?: osi3_Identifier_Raw[];
  vehicle_attributes?: osi3_MovingObject_VehicleAttributes_Raw;
  vehicle_classification?: osi3_MovingObject_VehicleClassification_Raw;
  model_reference?: string;
  future_trajectory?: osi3_StatePoint_Raw[];
  moving_object_classification?: osi3_MovingObject_MovingObjectClassification_Raw;
  source_reference?: osi3_ExternalReference_Raw[];
  color_description?: osi3_ColorDescription_Raw;
  pedestrian_attributes?: osi3_MovingObject_PedestrianAttributes_Raw;
}

export interface osi3_MovingObject_PedestrianAttributes_Raw {
  bbcenter_to_root?: osi3_Vector3d_Raw;
  skeleton_bone?: osi3_MovingObject_PedestrianAttributes_Bone_Raw[];
}

export interface osi3_MovingObject_PedestrianAttributes_Bone_Raw {
  type?: osi3_MovingObject_PedestrianAttributes_Bone_Type;
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
  length?: number;
  missing?: boolean;
  velocity?: osi3_Vector3d_Raw;
  orientation_rate?: osi3_Orientation3d_Raw;
}

export interface osi3_StatePoint_Raw {
  timestamp?: osi3_Timestamp_Raw;
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
}

export interface osi3_MovingObject_VehicleAttributes_Raw {
  driver_id?: osi3_Identifier_Raw;
  radius_wheel?: number;
  number_wheels?: number;
  bbcenter_to_rear?: osi3_Vector3d_Raw;
  bbcenter_to_front?: osi3_Vector3d_Raw;
  ground_clearance?: number;
  wheel_data?: osi3_MovingObject_VehicleAttributes_WheelData_Raw[];
  steering_wheel_angle?: number;
}

export interface osi3_MovingObject_VehicleAttributes_WheelData_Raw {
  axle?: number;
  index?: number;
  position?: osi3_Vector3d_Raw;
  wheel_radius?: number;
  rim_radius?: number;
  width?: number;
  orientation?: osi3_Orientation3d_Raw;
  rotation_rate?: number;
  model_reference?: string;
  friction_coefficient?: number;
}

export interface osi3_StationaryObject_Raw {
  id?: osi3_Identifier_Raw;
  base?: osi3_BaseStationary_Raw;
  classification?: osi3_StationaryObject_Classification_Raw;
  model_reference?: string;
  source_reference?: osi3_ExternalReference_Raw[];
  color_description?: osi3_ColorDescription_Raw;
}

export interface osi3_HostVehicleData_Raw {
  version?: osi3_InterfaceVersion_Raw;
  timestamp?: osi3_Timestamp_Raw;
  host_vehicle_id?: osi3_Identifier_Raw;
  location?: osi3_BaseMoving_Raw;
  location_rmse?: osi3_BaseMoving_Raw;
  vehicle_basics?: osi3_HostVehicleData_VehicleBasics_Raw;
  vehicle_powertrain?: osi3_HostVehicleData_VehiclePowertrain_Raw;
  vehicle_brake_system?: osi3_HostVehicleData_VehicleBrakeSystem_Raw;
  vehicle_steering?: osi3_HostVehicleData_VehicleSteering_Raw;
  vehicle_wheels?: osi3_HostVehicleData_VehicleWheels_Raw;
  vehicle_localization?: osi3_HostVehicleData_VehicleLocalization_Raw;
  vehicle_automated_driving_function?: osi3_HostVehicleData_VehicleAutomatedDrivingFunction_Raw[];
  vehicle_motion?: osi3_HostVehicleData_VehicleMotion_Raw;
  route?: osi3_Route_Raw;
}

export interface osi3_Route_Raw {
  route_id?: osi3_Identifier_Raw;
  route_segment?: osi3_Route_RouteSegment_Raw[];
}

export interface osi3_Route_RouteSegment_Raw {
  lane_segment?: osi3_Route_LogicalLaneSegment_Raw[];
}

export interface osi3_Route_LogicalLaneSegment_Raw {
  logical_lane_id?: osi3_Identifier_Raw;
  start_s?: number;
  end_s?: number;
}

export interface osi3_HostVehicleData_VehicleMotion_Raw {
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
  velocity?: osi3_Vector3d_Raw;
  orientation_rate?: osi3_Orientation3d_Raw;
  acceleration?: osi3_Vector3d_Raw;
  current_curvature?: number;
}

export interface osi3_HostVehicleData_VehicleAutomatedDrivingFunction_Raw {
  name?: osi3_HostVehicleData_VehicleAutomatedDrivingFunction_Name;
  custom_name?: string;
  state?: osi3_HostVehicleData_VehicleAutomatedDrivingFunction_State;
  custom_state?: string;
  driver_override?: osi3_HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Raw;
  custom_detail?: osi3_KeyValuePair_Raw[];
}

export interface osi3_KeyValuePair_Raw {
  key?: string;
  value?: string;
}

export interface osi3_HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Raw {
  active?: boolean;
  override_reason?: osi3_HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Reason[];
}

export interface osi3_HostVehicleData_VehicleLocalization_Raw {
  position?: osi3_Vector3d_Raw;
  orientation?: osi3_Orientation3d_Raw;
  geodetic_position?: osi3_GeodeticPosition_Raw;
}

export interface osi3_GeodeticPosition_Raw {
  longitude?: number;
  latitude?: number;
  altitude?: number;
}

export interface osi3_HostVehicleData_VehicleWheels_Raw {
  wheel_data?: osi3_HostVehicleData_VehicleWheels_WheelData_Raw[];
}

export interface osi3_HostVehicleData_VehicleWheels_WheelData_Raw {
  axle?: number;
  index?: number;
  rotation_rate?: number;
  slip?: number;
}

export interface osi3_HostVehicleData_VehicleSteering_Raw {
  vehicle_steering_wheel?: osi3_VehicleSteeringWheel_Raw;
}

export interface osi3_VehicleSteeringWheel_Raw {
  angle?: number;
  angular_speed?: number;
  torque?: number;
}

export interface osi3_HostVehicleData_VehicleBrakeSystem_Raw {
  pedal_position_brake?: number;
}

export interface osi3_HostVehicleData_VehiclePowertrain_Raw {
  pedal_position_acceleration?: number;
  pedal_position_clutch?: number;
  gear_transmission?: number;
  motor?: osi3_HostVehicleData_VehiclePowertrain_Motor_Raw[];
}

export interface osi3_HostVehicleData_VehiclePowertrain_Motor_Raw {
  type?: osi3_HostVehicleData_VehiclePowertrain_Motor_Type;
  rpm?: number;
  torque?: number;
}

export interface osi3_HostVehicleData_VehicleBasics_Raw {
  curb_weight?: number;
  operating_state?: osi3_HostVehicleData_VehicleBasics_OperatingState;
}

export type osi3_SensorData = osi3_SensorData_Raw;
export type osi3_Timestamp = osi3_Timestamp_Raw;
export type osi3_SensorData_VirtualDetectionArea = osi3_SensorData_VirtualDetectionArea_Raw;
export type osi3_Polygon3d = osi3_Polygon3d_Raw;
export type osi3_Vector3d = osi3_Vector3d_Raw;
export type osi3_LogicalDetectionData = osi3_LogicalDetectionData_Raw;
export type osi3_LogicalDetection = osi3_LogicalDetection_Raw;
export type osi3_Identifier = osi3_Identifier_Raw;
export type osi3_LogicalDetectionDataHeader = osi3_LogicalDetectionDataHeader_Raw;
export type osi3_InterfaceVersion = osi3_InterfaceVersion_Raw;
export type osi3_FeatureData = osi3_FeatureData_Raw;
export type osi3_CameraDetectionData = osi3_CameraDetectionData_Raw;
export type osi3_CameraPoint = osi3_CameraPoint_Raw;
export type osi3_Spherical3d = osi3_Spherical3d_Raw;
export type osi3_CameraDetection = osi3_CameraDetection_Raw;
export type osi3_ColorDescription = osi3_ColorDescription_Raw;
export type osi3_ColorCMYK = osi3_ColorCMYK_Raw;
export type osi3_ColorLUV = osi3_ColorLUV_Raw;
export type osi3_ColorHSV = osi3_ColorHSV_Raw;
export type osi3_ColorRGBIR = osi3_ColorRGBIR_Raw;
export type osi3_ColorRGB = osi3_ColorRGB_Raw;
export type osi3_ColorGrey = osi3_ColorGrey_Raw;
export type osi3_CameraDetectionSpecificHeader = osi3_CameraDetectionSpecificHeader_Raw;
export type osi3_SensorDetectionHeader = osi3_SensorDetectionHeader_Raw;
export type osi3_MountingPosition = osi3_MountingPosition_Raw;
export type osi3_Orientation3d = osi3_Orientation3d_Raw;
export type osi3_UltrasonicDetectionData = osi3_UltrasonicDetectionData_Raw;
export type osi3_UltrasonicIndirectDetection = osi3_UltrasonicIndirectDetection_Raw;
export type osi3_UltrasonicDetection = osi3_UltrasonicDetection_Raw;
export type osi3_UltrasonicDetectionSpecificHeader = osi3_UltrasonicDetectionSpecificHeader_Raw;
export type osi3_LidarDetectionData = osi3_LidarDetectionData_Raw;
export type osi3_LidarDetection = osi3_LidarDetection_Raw;
export type osi3_RadarDetectionData = osi3_RadarDetectionData_Raw;
export type osi3_RadarDetection = osi3_RadarDetection_Raw;
export type osi3_DetectedOccupant = osi3_DetectedOccupant_Raw;
export type osi3_DetectedOccupant_CandidateOccupant = osi3_DetectedOccupant_CandidateOccupant_Raw;
export type osi3_Occupant_Classification = osi3_Occupant_Classification_Raw;
export type osi3_DetectedItemHeader = osi3_DetectedItemHeader_Raw;
export type osi3_DetectedEntityHeader = osi3_DetectedEntityHeader_Raw;
export type osi3_DetectedLane = osi3_DetectedLane_Raw;
export type osi3_DetectedLane_CandidateLane = osi3_DetectedLane_CandidateLane_Raw;
export type osi3_Lane_Classification = osi3_Lane_Classification_Raw;
export type osi3_Lane_Classification_RoadCondition = osi3_Lane_Classification_RoadCondition_Raw;
export type osi3_Lane_Classification_LanePairing = osi3_Lane_Classification_LanePairing_Raw;
export type osi3_DetectedLaneBoundary = osi3_DetectedLaneBoundary_Raw;
export type osi3_LaneBoundary_BoundaryPoint = osi3_LaneBoundary_BoundaryPoint_Raw;
export type osi3_DetectedLaneBoundary_CandidateLaneBoundary = osi3_DetectedLaneBoundary_CandidateLaneBoundary_Raw;
export type osi3_LaneBoundary_Classification = osi3_LaneBoundary_Classification_Raw;
export type osi3_DetectedRoadMarking = osi3_DetectedRoadMarking_Raw;
export type osi3_DetectedRoadMarking_CandidateRoadMarking = osi3_DetectedRoadMarking_CandidateRoadMarking_Raw;
export type osi3_RoadMarking_Classification = osi3_RoadMarking_Classification_Raw;
export type osi3_LogicalLaneAssignment = osi3_LogicalLaneAssignment_Raw;
export type osi3_TrafficSignValue = osi3_TrafficSignValue_Raw;
export type osi3_BaseStationary = osi3_BaseStationary_Raw;
export type osi3_BoundingBox = osi3_BoundingBox_Raw;
export type osi3_Dimension3d = osi3_Dimension3d_Raw;
export type osi3_Vector2d = osi3_Vector2d_Raw;
export type osi3_DetectedTrafficLight = osi3_DetectedTrafficLight_Raw;
export type osi3_DetectedTrafficLight_CandidateTrafficLight = osi3_DetectedTrafficLight_CandidateTrafficLight_Raw;
export type osi3_TrafficLight_Classification = osi3_TrafficLight_Classification_Raw;
export type osi3_DetectedTrafficSign = osi3_DetectedTrafficSign_Raw;
export type osi3_DetectedTrafficSign_DetectedSupplementarySign = osi3_DetectedTrafficSign_DetectedSupplementarySign_Raw;
export type osi3_DetectedTrafficSign_DetectedSupplementarySign_CandidateSupplementarySign = osi3_DetectedTrafficSign_DetectedSupplementarySign_CandidateSupplementarySign_Raw;
export type osi3_TrafficSign_SupplementarySign_Classification = osi3_TrafficSign_SupplementarySign_Classification_Raw;
export type osi3_TrafficSign_SupplementarySign_Classification_Arrow = osi3_TrafficSign_SupplementarySign_Classification_Arrow_Raw;
export type osi3_DetectedTrafficSign_DetectedMainSign = osi3_DetectedTrafficSign_DetectedMainSign_Raw;
export type osi3_DetectedTrafficSign_DetectedMainSign_CandidateMainSign = osi3_DetectedTrafficSign_DetectedMainSign_CandidateMainSign_Raw;
export type osi3_TrafficSign_MainSign_Classification = osi3_TrafficSign_MainSign_Classification_Raw;
export type osi3_DetectedMovingObject = osi3_DetectedMovingObject_Raw;
export type osi3_UltrasonicSpecificObjectData = osi3_UltrasonicSpecificObjectData_Raw;
export type osi3_UltrasonicSpecificObjectData_Signalway = osi3_UltrasonicSpecificObjectData_Signalway_Raw;
export type osi3_CameraSpecificObjectData = osi3_CameraSpecificObjectData_Raw;
export type osi3_LidarSpecificObjectData = osi3_LidarSpecificObjectData_Raw;
export type osi3_RadarSpecificObjectData = osi3_RadarSpecificObjectData_Raw;
export type osi3_DetectedMovingObject_CandidateMovingObject = osi3_DetectedMovingObject_CandidateMovingObject_Raw;
export type osi3_MovingObject_MovingObjectClassification = osi3_MovingObject_MovingObjectClassification_Raw;
export type osi3_MovingObject_VehicleClassification = osi3_MovingObject_VehicleClassification_Raw;
export type osi3_MovingObject_VehicleClassification_LightState = osi3_MovingObject_VehicleClassification_LightState_Raw;
export type osi3_BaseMoving = osi3_BaseMoving_Raw;
export type osi3_DetectedStationaryObject = osi3_DetectedStationaryObject_Raw;
export type osi3_DetectedStationaryObject_CandidateStationaryObject = osi3_DetectedStationaryObject_CandidateStationaryObject_Raw;
export type osi3_StationaryObject_Classification = osi3_StationaryObject_Classification_Raw;
export type osi3_StationaryObject_Classification_EmittingStructureAttribute = osi3_StationaryObject_Classification_EmittingStructureAttribute_Raw;
export type osi3_SpatialSignalStrength = osi3_SpatialSignalStrength_Raw;
export type osi3_WavelengthData = osi3_WavelengthData_Raw;
export type osi3_SensorView = osi3_SensorView_Raw;
export type osi3_UltrasonicSensorView = osi3_UltrasonicSensorView_Raw;
export type osi3_UltrasonicSensorViewConfiguration = osi3_UltrasonicSensorViewConfiguration_Raw;
export type osi3_CameraSensorView = osi3_CameraSensorView_Raw;
export type osi3_CameraSensorViewConfiguration = osi3_CameraSensorViewConfiguration_Raw;
export type osi3_LidarSensorView = osi3_LidarSensorView_Raw;
export type osi3_LidarSensorView_Reflection = osi3_LidarSensorView_Reflection_Raw;
export type osi3_LidarSensorViewConfiguration = osi3_LidarSensorViewConfiguration_Raw;
export type osi3_RadarSensorView = osi3_RadarSensorView_Raw;
export type osi3_RadarSensorView_Reflection = osi3_RadarSensorView_Reflection_Raw;
export type osi3_RadarSensorViewConfiguration = osi3_RadarSensorViewConfiguration_Raw;
export type osi3_RadarSensorViewConfiguration_AntennaDiagramEntry = osi3_RadarSensorViewConfiguration_AntennaDiagramEntry_Raw;
export type osi3_GenericSensorView = osi3_GenericSensorView_Raw;
export type osi3_GenericSensorViewConfiguration = osi3_GenericSensorViewConfiguration_Raw;
export type osi3_GroundTruth = osi3_GroundTruth_Raw;
export type osi3_GroundTruth_ProjFrameOffset = osi3_GroundTruth_ProjFrameOffset_Raw;
export type osi3_LogicalLane = osi3_LogicalLane_Raw;
export type osi3_LogicalLane_TrafficRule = osi3_LogicalLane_TrafficRule_Raw;
export type osi3_LogicalLane_TrafficRule_SpeedLimit = osi3_LogicalLane_TrafficRule_SpeedLimit_Raw;
export type osi3_LogicalLane_TrafficRule_TrafficRuleValidity = osi3_LogicalLane_TrafficRule_TrafficRuleValidity_Raw;
export type osi3_LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity = osi3_LogicalLane_TrafficRule_TrafficRuleValidity_TypeValidity_Raw;
export type osi3_LogicalLane_LaneConnection = osi3_LogicalLane_LaneConnection_Raw;
export type osi3_LogicalLane_LaneRelation = osi3_LogicalLane_LaneRelation_Raw;
export type osi3_LogicalLane_PhysicalLaneReference = osi3_LogicalLane_PhysicalLaneReference_Raw;
export type osi3_ExternalReference = osi3_ExternalReference_Raw;
export type osi3_LogicalLaneBoundary = osi3_LogicalLaneBoundary_Raw;
export type osi3_LogicalLaneBoundary_LogicalBoundaryPoint = osi3_LogicalLaneBoundary_LogicalBoundaryPoint_Raw;
export type osi3_ReferenceLine = osi3_ReferenceLine_Raw;
export type osi3_ReferenceLine_ReferenceLinePoint = osi3_ReferenceLine_ReferenceLinePoint_Raw;
export type osi3_EnvironmentalConditions = osi3_EnvironmentalConditions_Raw;
export type osi3_EnvironmentalConditions_Sun = osi3_EnvironmentalConditions_Sun_Raw;
export type osi3_EnvironmentalConditions_Wind = osi3_EnvironmentalConditions_Wind_Raw;
export type osi3_EnvironmentalConditions_CloudLayer = osi3_EnvironmentalConditions_CloudLayer_Raw;
export type osi3_EnvironmentalConditions_TimeOfDay = osi3_EnvironmentalConditions_TimeOfDay_Raw;
export type osi3_Occupant = osi3_Occupant_Raw;
export type osi3_Lane = osi3_Lane_Raw;
export type osi3_LaneBoundary = osi3_LaneBoundary_Raw;
export type osi3_RoadMarking = osi3_RoadMarking_Raw;
export type osi3_TrafficLight = osi3_TrafficLight_Raw;
export type osi3_TrafficSign = osi3_TrafficSign_Raw;
export type osi3_TrafficSign_SupplementarySign = osi3_TrafficSign_SupplementarySign_Raw;
export type osi3_TrafficSign_MainSign = osi3_TrafficSign_MainSign_Raw;
export type osi3_MovingObject = osi3_MovingObject_Raw;
export type osi3_MovingObject_PedestrianAttributes = osi3_MovingObject_PedestrianAttributes_Raw;
export type osi3_MovingObject_PedestrianAttributes_Bone = osi3_MovingObject_PedestrianAttributes_Bone_Raw;
export type osi3_StatePoint = osi3_StatePoint_Raw;
export type osi3_MovingObject_VehicleAttributes = osi3_MovingObject_VehicleAttributes_Raw;
export type osi3_MovingObject_VehicleAttributes_WheelData = osi3_MovingObject_VehicleAttributes_WheelData_Raw;
export type osi3_StationaryObject = osi3_StationaryObject_Raw;
export type osi3_HostVehicleData = osi3_HostVehicleData_Raw;
export type osi3_Route = osi3_Route_Raw;
export type osi3_Route_RouteSegment = osi3_Route_RouteSegment_Raw;
export type osi3_Route_LogicalLaneSegment = osi3_Route_LogicalLaneSegment_Raw;
export type osi3_HostVehicleData_VehicleMotion = osi3_HostVehicleData_VehicleMotion_Raw;
export type osi3_HostVehicleData_VehicleAutomatedDrivingFunction = osi3_HostVehicleData_VehicleAutomatedDrivingFunction_Raw;
export type osi3_KeyValuePair = osi3_KeyValuePair_Raw;
export type osi3_HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride = osi3_HostVehicleData_VehicleAutomatedDrivingFunction_DriverOverride_Raw;
export type osi3_HostVehicleData_VehicleLocalization = osi3_HostVehicleData_VehicleLocalization_Raw;
export type osi3_GeodeticPosition = osi3_GeodeticPosition_Raw;
export type osi3_HostVehicleData_VehicleWheels = osi3_HostVehicleData_VehicleWheels_Raw;
export type osi3_HostVehicleData_VehicleWheels_WheelData = osi3_HostVehicleData_VehicleWheels_WheelData_Raw;
export type osi3_HostVehicleData_VehicleSteering = osi3_HostVehicleData_VehicleSteering_Raw;
export type osi3_VehicleSteeringWheel = osi3_VehicleSteeringWheel_Raw;
export type osi3_HostVehicleData_VehicleBrakeSystem = osi3_HostVehicleData_VehicleBrakeSystem_Raw;
export type osi3_HostVehicleData_VehiclePowertrain = osi3_HostVehicleData_VehiclePowertrain_Raw;
export type osi3_HostVehicleData_VehiclePowertrain_Motor = osi3_HostVehicleData_VehiclePowertrain_Motor_Raw;
export type osi3_HostVehicleData_VehicleBasics = osi3_HostVehicleData_VehicleBasics_Raw;

export type GroundTruthRaw = osi3_GroundTruth_Raw;
export type SensorViewRaw = osi3_SensorView_Raw;
export type SensorDataRaw = osi3_SensorData_Raw;

export type GroundTruth = GroundTruthRaw;
export type SensorView = SensorViewRaw;
export type SensorData = SensorDataRaw;
